class Categories {
  static const List<String> allCategories = [
    'Animals',
    'Movies',
    'Food',
    'Sports',
    'Music',
    'Countries',
    'Celebrities',
    'Professions',
    'Science',
    'Technology',
    'Literature',
    'History',
    'Art',
    'TV Shows',
    'Brands',
    'Mythology',
    'Video Games',
    'Nature',
    'Fashion',
    'Inventions',
  ];

  static const Map<String, List<String>> categoryWords = {
    'Animals': [
      'Elephant', 'Lion', 'Giraffe', 'Penguin', 'Kangaroo', 'Dolphin', 'Koala', 'Tiger', 'Panda', 'Cheetah',
      'Octopus', 'Platypus', 'Flamingo', 'Sloth', 'Narwhal', 'Rhinoceros', 'Hippopotamus', 'Zebra', 'Gorilla', 'Chimpanzee',
      'Orangutan', 'Leopard', 'Jaguar', 'Polar Bear', 'Grizzly Bear', 'Koala', 'Red Panda', 'Lemur', 'Meerkat', 'Raccoon',
      'Fox', 'Wolf', 'Coyote', 'Hyena', 'Jackal', 'Lynx', 'Bobcat', 'Mountain Lion', 'Panther', 'Cougar',
      'Ocelot', 'Serval', 'Caracal', 'Cheetah', 'Leopard', 'Snow Leopard', 'Jaguar', 'Tiger', 'Lion', 'Puma',
      'Elephant Seal', 'Sea Lion', 'Walrus', 'Manatee', 'Dugong', 'Whale Shark', 'Great White Shark', 'Hammerhead Shark', 'Manta Ray', 'Stingray',
      'Seahorse', 'Clownfish', 'Angelfish', 'Pufferfish', 'Swordfish', 'Marlin', 'Tuna', 'Salmon', 'Trout', 'Bass',
      'Catfish', 'Carp', 'Piranha', 'Barracuda', 'Moray Eel', 'Electric Eel', 'Jellyfish', 'Squid', 'Cuttlefish', 'Nautilus',
      'Lobster', 'Crab', 'Shrimp', 'Crayfish', 'Hermit Crab', 'Horseshoe Crab', 'Starfish', 'Sea Urchin', 'Sea Cucumber', 'Coral',
      'Anemone', 'Sponge', 'Barnacle', 'Mussel', 'Clam', 'Oyster', 'Scallop', 'Conch', 'Snail', 'Slug',
      'Butterfly', 'Moth', 'Dragonfly', 'Damselfly', 'Ladybug', 'Beetle', 'Ant', 'Bee', 'Wasp', 'Hornet',
      'Grasshopper', 'Cricket', 'Katydid', 'Praying Mantis', 'Stick Insect', 'Cockroach', 'Termite', 'Earwig', 'Flea', 'Louse',
      'Mosquito', 'Fly', 'Gnat', 'Midge', 'Firefly', 'Glowworm', 'Centipede', 'Millipede', 'Scorpion', 'Spider',
      'Tarantula', 'Black Widow', 'Daddy Long Legs', 'Tick', 'Mite', 'Worm', 'Leech', 'Planarian', 'Flatworm', 'Roundworm',
      'Tapeworm',
    ],
    'Movies': [
      'The Godfather', 'Citizen Kane', 'Casablanca', 'Schindler\'s List', 'Raging Bull', 'Gone with the Wind', 'Lawrence of Arabia', 'The Wizard of Oz', 'One Flew Over the Cuckoo\'s Nest', 'The Graduate',
      'On the Waterfront', 'Sunset Boulevard', 'It\'s a Wonderful Life', 'Star Wars', 'The Lord of the Rings', 'Pulp Fiction', 'Goodfellas', 'The Matrix', 'Forrest Gump', 'The Silence of the Lambs',
      'Apocalypse Now', 'Gladiator', 'Saving Private Ryan', 'Titanic', 'The Shawshank Redemption', 'Braveheart', 'The Dark Knight', 'Inception', 'The Green Mile', 'Fight Club',
      'The Usual Suspects', 'Jurassic Park', 'Back to the Future', 'The Lion King', 'Alien', 'Blade Runner', 'Terminator 2: Judgment Day', 'The Shining', 'Jaws', 'E.T. the Extra-Terrestrial',
      'Raiders of the Lost Ark', 'The Sixth Sense', 'The Exorcist', 'Psycho', 'Vertigo', 'North by Northwest', 'Rear Window', 'A Clockwork Orange', '2001: A Space Odyssey', 'The Departed',
      'Taxi Driver', 'American Beauty', 'Eternal Sunshine of the Spotless Mind', 'The Pianist', 'Memento', 'The Prestige', 'Amélie', 'Pan\'s Labyrinth', 'The Big Lebowski', 'No Country for Old Men',
      'There Will Be Blood', 'The Social Network', 'The King\'s Speech', 'Black Swan', 'Inglourious Basterds', 'The Grand Budapest Hotel', 'Whiplash', 'La La Land', 'Moonlight', 'Parasite',
      'The Shape of Water', 'Three Billboards Outside Ebbing, Missouri', 'Get Out', 'Lady Bird', 'Dunkirk', 'Mad Max: Fury Road', 'The Revenant', 'Birdman', 'Boyhood', '12 Years a Slave',
      'Gravity', 'Her', 'The Wolf of Wall Street', 'Django Unchained', 'The Artist', 'The Tree of Life', 'Inception', 'The Hurt Locker', 'Slumdog Millionaire', 'No Country for Old Men',
      'The Departed', 'Crash', 'Million Dollar Baby', 'The Lord of the Rings: The Return of the King', 'Chicago', 'A Beautiful Mind', 'Gladiator', 'American Beauty', 'Shakespeare in Love', 'Titanic',
      'The English Patient', 'Braveheart', 'Forrest Gump', 'Schindler\'s List', 'Unforgiven', 'The Silence of the Lambs', 'Dances with Wolves', 'Driving Miss Daisy', 'Rain Man', 'The Last Emperor',
      'Platoon', 'Out of Africa', 'Amadeus', 'Terms of Endearment', 'Gandhi', 'Chariots of Fire', 'Ordinary People', 'Kramer vs. Kramer', 'The Deer Hunter', 'Annie Hall',
      'Rocky', 'One Flew Over the Cuckoo\'s Nest', 'The Godfather Part II', 'The Sting', 'The Godfather', 'The French Connection', 'Patton', 'Midnight Cowboy', 'Oliver!', 'In the Heat of the Night',
      'A Man for All Seasons', 'The Sound of Music', 'My Fair Lady', 'Tom Jones', 'Lawrence of Arabia', 'West Side Story', 'The Apartment', 'Ben-Hur', 'Gigi', 'The Bridge on the River Kwai',
      'Around the World in 80 Days', 'Marty', 'On the Waterfront', 'From Here to Eternity', 'The Greatest Show on Earth', 'An American in Paris', 'All About Eve', 'All the King\'s Men', 'Hamlet', 'Gentleman\'s Agreement',
      'The Best Years of Our Lives', 'The Lost Weekend', 'Going My Way', 'Casablanca', 'Mrs. Miniver', 'How Green Was My Valley', 'Rebecca', 'Gone with the Wind', 'You Can\'t Take It with You', 'The Life of Emile Zola',
      'The Great Ziegfeld', 'Mutiny on the Bounty', 'It Happened One Night', 'Cavalcade', 'Grand Hotel', 'Cimarron', 'All Quiet on the Western Front', 'The Broadway Melody', 'Wings', 'Sunrise: A Song of Two Humans',
      'The Jazz Singer', 'Don Juan', 'The Big Parade', 'The Gold Rush', 'The Thief of Bagdad', 'The Ten Commandments', 'The Covered Wagon', 'The Four Horsemen of the Apocalypse', 'Way Down East', 'Intolerance',
    ],
    'Food': [
      'Pizza', 'Hamburger', 'Sushi', 'Pasta', 'Tacos', 'Fried Chicken', 'Steak', 'Ice Cream', 'Chocolate', 'Cheese',
      'Bacon', 'Eggs', 'Pancakes', 'Waffles', 'French Toast', 'Cereal', 'Oatmeal', 'Yogurt', 'Bagel', 'Croissant',
      'Donut', 'Muffin', 'Cupcake', 'Cake', 'Pie', 'Cookies', 'Brownies', 'Fudge', 'Caramel', 'Popcorn',
      'Chips', 'Pretzels', 'Nachos', 'Guacamole', 'Salsa', 'Hummus', 'Falafel', 'Pita Bread', 'Naan', 'Roti',
      'Curry', 'Biryani', 'Tandoori Chicken', 'Pad Thai', 'Spring Rolls', 'Dumplings', 'Fried Rice', 'Lo Mein', 'Chow Mein', 'General Tso\'s Chicken',
      'Kung Pao Chicken', 'Sweet and Sour Pork', 'Peking Duck', 'Dim Sum', 'Ramen', 'Udon', 'Soba', 'Tempura', 'Teriyaki', 'Miso Soup',
      'Pho', 'Banh Mi', 'Bun Bo Hue', 'Papaya Salad', 'Tom Yum Soup', 'Massaman Curry', 'Green Curry', 'Red Curry', 'Panang Curry', 'Satay',
      'Nasi Goreng', 'Rendang', 'Laksa', 'Hainanese Chicken Rice', 'Char Kway Teow', 'Chili Crab', 'Hokkien Mee', 'Roti Canai', 'Mee Goreng', 'Bak Kut Teh',
      'Paella', 'Gazpacho', 'Tortilla Española', 'Patatas Bravas', 'Chorizo', 'Jamón Ibérico', 'Manchego Cheese', 'Croquetas', 'Calamari', 'Gambas al Ajillo',
      'Lasagna', 'Risotto', 'Osso Buco', 'Gnocchi', 'Carbonara', 'Cacio e Pepe', 'Arancini', 'Bruschetta', 'Caprese Salad', 'Tiramisu',
      'Baguette', 'Quiche', 'Crème Brûlée', 'Escargot', 'Coq au Vin', 'Bouillabaisse', 'Ratatouille', 'Cassoulet', 'Beef Bourguignon', 'Macaron',
      'Schnitzel', 'Bratwurst', 'Sauerkraut', 'Spätzle', 'Kartoffelpuffer', 'Sauerbraten', 'Rouladen', 'Brezel', 'Apfelstrudel', 'Black Forest Cake',
      'Fish and Chips', 'Shepherd\'s Pie', 'Bangers and Mash', 'Full English Breakfast', 'Sunday Roast', 'Beef Wellington', 'Toad in the Hole', 'Sticky Toffee Pudding', 'Trifle', 'Eton Mess',
      'Haggis', 'Scotch Egg', 'Cornish Pasty', 'Welsh Rarebit', 'Lancashire Hotpot', 'Bubble and Squeak', 'Spotted Dick', 'Jam Roly-Poly', 'Battenberg Cake', 'Victoria Sponge',
      'Poutine', 'Maple Syrup', 'Butter Tart', 'Nanaimo Bar', 'Beaver Tail', 'Montreal-Style Bagel', 'Peameal Bacon', 'Tourtière', 'Bannock', 'Saskatoon Berry Pie',
      'Vegemite', 'Meat Pie', 'Pavlova', 'Lamington', 'Tim Tam', 'Anzac Biscuit', 'Fairy Bread', 'Kangaroo', 'Barramundi', 'Witchetty Grub',
      'Feijoada', 'Churrasco', 'Moqueca', 'Pão de Queijo', 'Brigadeiro', 'Acarajé', 'Coxinha', 'Farofa', 'Açaí Bowl', 'Guaraná',
      'Kimchi', 'Bibimbap', 'Bulgogi', 'Japchae', 'Samgyeopsal', 'Tteokbokki', 'Sundubu-jjigae', 'Samgyetang', 'Bossam', 'Hotteok',
      'Borscht', 'Beef Stroganoff', 'Pelmeni', 'Blini', 'Caviar', 'Shashlik', 'Olivier Salad', 'Kvass', 'Kasha', 'Pirozhki',
    ],
    'Sports': [
      "LeBron James", "Michael Jordan", "Tom Brady", "Lionel Messi", "Cristiano Ronaldo",
      "Serena Williams", "Roger Federer", "Tiger Woods", "Usain Bolt", "Simone Biles",
      "Rafael Nadal", "Novak Djokovic", "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo",
      "Kobe Bryant", "Shaquille O'Neal", "Wayne Gretzky", "Sidney Crosby", "Alex Ovechkin",
      "Mike Trout", "Mookie Betts", "Aaron Judge", "Bryce Harper", "Clayton Kershaw",
      "Patrick Mahomes", "Aaron Rodgers", "Drew Brees", "Russell Wilson", "Lamar Jackson",
      "Saquon Barkley", "Christian McCaffrey", "Ezekiel Elliott", "Derrick Henry", "Alvin Kamara",
      "Anthony Davis", "Kawhi Leonard", "James Harden", "Chris Paul", "Paul George",
      "Damian Lillard", "Russell Westbrook", "Kyrie Irving", "Luka Dončić", "Zion Williamson",
      "Joel Embiid", "Nikola Jokić", "Karl-Anthony Towns", "Devin Booker", "Jayson Tatum",
      "Jimmy Butler", "Klay Thompson", "Draymond Green", "Kemba Walker", "Trae Young",
      "Ja Morant", "Donovan Mitchell", "Rudy Gobert", "Bam Adebayo", "De'Aaron Fox",
      "Bradley Beal", "CJ McCollum", "Jrue Holiday", "Kyle Lowry", "Pascal Siakam",
      "Blake Griffin", "Andre Drummond", "Nikola Vučević", "Lauri Markkanen", "Kristaps Porziņģis",
      "DeMar DeRozan", "Zach LaVine", "John Wall", "Victor Oladipo", "D'Angelo Russell",
      "Brooklyn Nets", "Golden State Warriors", "Los Angeles Lakers", "Chicago Bulls", "Miami Heat",
      "Boston Celtics", "Philadelphia 76ers", "Milwaukee Bucks", "Toronto Raptors", "Houston Rockets",
      "Dallas Mavericks", "San Antonio Spurs", "Phoenix Suns", "Sacramento Kings", "Portland Trail Blazers",
      "Oklahoma City Thunder", "Utah Jazz", "Denver Nuggets", "Minnesota Timberwolves", "New Orleans Pelicans",
      "Atlanta Hawks", "Charlotte Hornets", "Washington Wizards", "Cleveland Cavaliers", "Detroit Pistons",
      "Indiana Pacers", "Orlando Magic", "New York Knicks", "Los Angeles Clippers", "Memphis Grizzlies",
      "New England Patriots", "Dallas Cowboys", "San Francisco 49ers", "Kansas City Chiefs", "Green Bay Packers",
      "Pittsburgh Steelers", "Seattle Seahawks", "Baltimore Ravens", "Chicago Bears", "Minnesota Vikings",
      "New Orleans Saints", "Buffalo Bills", "Tennessee Titans", "Indianapolis Colts", "Los Angeles Rams",
      "Cleveland Browns", "Tampa Bay Buccaneers", "Miami Dolphins", "Las Vegas Raiders", "Arizona Cardinals",
      "Washington Football Team", "New York Giants", "Philadelphia Eagles", "Denver Broncos", "Carolina Panthers",
      "Atlanta Falcons", "Detroit Lions", "Houston Texans", "Cincinnati Bengals", "Jacksonville Jaguars",
      "New York Yankees", "Los Angeles Dodgers", "Boston Red Sox", "Chicago Cubs", "San Francisco Giants",
      "St. Louis Cardinals", "Houston Astros", "Atlanta Braves", "New York Mets", "Philadelphia Phillies",
      "San Diego Padres", "Milwaukee Brewers", "Washington Nationals", "Minnesota Twins", "Cleveland Indians",
      "Chicago White Sox", "Cincinnati Reds", "Toronto Blue Jays", "Kansas City Royals", "Oakland Athletics",
      "Seattle Mariners", "Tampa Bay Rays", "Texas Rangers", "Los Angeles Angels", "Miami Marlins",
      "Arizona Diamondbacks", "Pittsburgh Pirates", "Colorado Rockies", "Baltimore Orioles", "Detroit Tigers",
      "Manchester United", "Liverpool FC", "FC Barcelona", "Real Madrid", "Chelsea FC",
      "Manchester City", "Paris Saint-Germain", "Juventus", "Bayern Munich", "AC Milan",
      "Inter Milan", "Arsenal FC", "Tottenham Hotspur", "Atletico Madrid", "Borussia Dortmund",
      "Ajax", "FC Porto", "Benfica", "AS Roma", "Lazio",
      "Napoli", "Sevilla FC", "Villarreal CF", "RB Leipzig", "PSV Eindhoven",
      "Olympique Lyonnais", "Marseille", "Club Brugge", "Shakhtar Donetsk", "Zenit Saint Petersburg",
      "Sporting CP", "Celtic FC", "Rangers FC", "Galatasaray", "Fenerbahçe",
      "Olympiacos", "AEK Athens", "CSKA Moscow", "Lokomotiv Moscow", "Besiktas",
      "Valencia CF", "Real Sociedad", "Eintracht Frankfurt", "Wolfsburg", "Borussia Mönchengladbach",
      "Soccer", "Basketball", "Baseball", "Tennis", "Golf", "Cricket", "Rugby", "American Football",
      "Hockey", "Table Tennis", "Badminton", "Volleyball", "Swimming", "Athletics", "Cycling",
      "Boxing", "Wrestling", "Gymnastics", "Martial Arts", "Surfing", "Skateboarding", "Skiing",
      "Snowboarding", "Equestrian", "Fencing", "Handball", "Lacrosse", "Rowing", "Sailing", "Softball",
      "Squash", "Triathlon", "Weightlifting", "Archery", "Darts", "Snooker", "Billiards", "Chess",
      "Polo", "Karate", "Judo", "Taekwondo", "Kendo", "Sumo", "Muay Thai", "Kickboxing", "MMA",
      "Formula 1", "NASCAR", "Rally", "IndyCar", "Speedway", "Tour de France", "Ironman", "Marathon",
      "Sprint", "Hurdles", "High Jump", "Long Jump", "Pole Vault", "Shot Put", "Discus", "Javelin",
      "Decathlon", "Pentathlon", "Heptathlon", "Biathlon", "Cross Country", "Nordic Combined",
      "Skeleton", "Luge", "Bobsleigh", "Curling", "Ice Skating", "Figure Skating", "Speed Skating",
      "Field Hockey", "Ice Hockey", "Water Polo", "Kayaking", "Canoeing", "Dragon Boat", "Synchronized Swimming",
      "Diving", "Platform Diving", "Springboard Diving", "Open Water Swimming", "Futsal", "Beach Volleyball",
      "Beach Soccer", "Footgolf", "Ultimate Frisbee", "Disc Golf", "Racquetball", "Paddle Tennis", "Pickleball",
      "Petanque", "Boules", "Bocce", "Kite Surfing", "Wind Surfing", "Wakeboarding", "Water Skiing", "Bodyboarding",
      "Sandboarding", "Mountain Biking", "Downhill Mountain Biking", "Freestyle BMX", "Flatland BMX",
      "Street Luge", "Roller Skating", "Roller Derby", "Parkour", "Freerunning", "Rock Climbing", "Bouldering",
      "Speed Climbing", "Sport Climbing", "Ice Climbing", "Caving", "Spelunking", "Orienteering", "Geocaching",
      "Rogaining", "Adventure Racing", "Obstacle Course Racing", "Mud Run", "Tough Mudder", "Spartan Race",
      "Strongman", "Powerlifting", "Bodybuilding", "CrossFit", "Highland Games", "E-Sports", "Video Game Tournaments",
    ],
    'Music': [
      "Pop", "Rock", "Hip Hop", "Rap", "Country", "Jazz", "Blues", "Classical",
      "Electronic", "Dance", "R&B", "Soul", "Reggae", "Funk", "Disco", "Heavy Metal",
      "Punk", "Alternative", "Indie", "Folk", "Gospel", "Opera", "Ska", "Bluegrass",
      "Latin", "Salsa", "Reggaeton", "Bachata", "Merengue", "Flamenco", "Afrobeat",
      "K-Pop", "J-Pop", "EDM", "House", "Techno", "Trance", "Dubstep", "Drum and Bass",
      "Trap", "Lo-fi", "Ambient", "New Age", "Synthwave", "Chillwave", "Grunge", "Britpop",
      "Post-rock", "Shoegaze", "Dream Pop", "Art Rock", "Progressive Rock", "Hard Rock",
      "Glam Rock", "Arena Rock", "Soft Rock", "Folk Rock", "Psychedelic Rock", "Symphonic Rock",
      "Rap Rock", "Industrial", "Noise", "Trip Hop", "Acoustic", "Unplugged", "Easy Listening",
      "Lounge", "Soundtrack", "Theme Music", "Instrumental", "A Cappella", "Vocal",
      "Baroque", "Renaissance", "Romantic", "Contemporary Classical", "Minimalism",
      "Experimental", "World Music", "Celtic", "Meditation Music", "Yoga Music",
      "Workout Music", "Chillout", "Deep House", "Future Bass", "Tropical House",
      "Electro Swing", "Moombahton", "Latin Trap", "Mariachi", "Ranchera", "Bolero",
      "Cumbia", "Tejano", "Norteño", "Tango", "Bossa Nova", "Samba", "Pagode", "Forró",
      "Frevo", "Axé", "Lambada", "Maracatu", "MPB (Música Popular Brasileira)",
      "Bach", "Mozart", "Beethoven", "Chopin", "Tchaikovsky", "Vivaldi", "Handel",
      "Debussy", "Ravel", "Gershwin", "Stravinsky", "Shostakovich", "Brahms", "Schubert",
      "Liszt", "Mendelssohn", "Dvorak", "Sibelius", "Mahler", "Rachmaninoff", "Paganini",
      "Elvis Presley", "The Beatles", "The Rolling Stones", "Led Zeppelin", "Pink Floyd",
      "Queen", "David Bowie", "Elton John", "Billy Joel", "Stevie Wonder", "Marvin Gaye",
      "James Brown", "Aretha Franklin", "Prince", "Michael Jackson", "Madonna", "Whitney Houston",
      "Mariah Carey", "Celine Dion", "Beyoncé", "Adele", "Rihanna", "Taylor Swift",
      "Katy Perry", "Lady Gaga", "Bruno Mars", "Justin Timberlake", "Ed Sheeran", "Sam Smith",
      "Ariana Grande", "Billie Eilish", "Shawn Mendes", "Dua Lipa", "Post Malone", "Drake",
      "Kanye West", "Jay-Z", "Eminem", "Snoop Dogg", "Kendrick Lamar", "Travis Scott",
      "Cardi B", "Nicki Minaj", "Megan Thee Stallion", "J. Cole", "Lil Wayne", "Nas",
      "Wu-Tang Clan", "Public Enemy", "N.W.A", "Run-D.M.C.", "LL Cool J", "Ice-T",
      "Outkast", "A Tribe Called Quest", "The Notorious B.I.G.", "2Pac", "50 Cent",
      "Usher", "Chris Brown", "Justin Bieber", "Shakira", "Jennifer Lopez", "Pitbull",
      "Enrique Iglesias", "Luis Fonsi", "Daddy Yankee", "Ozuna", "Bad Bunny", "J Balvin",
      "Maluma", "Ricky Martin", "Gloria Estefan", "Marc Anthony", "Juanes", "Carlos Vives",
      "Julio Iglesias", "Alejandro Sanz", "Camila Cabello", "Selena Gomez", "Demi Lovato",
      "Frank Sinatra", "Dean Martin", "Tony Bennett", "Nat King Cole", "Bing Crosby",
      "Ella Fitzgerald", "Billie Holiday", "Louis Armstrong", "Duke Ellington", "Miles Davis",
      "John Coltrane", "Charlie Parker", "Thelonious Monk", "Dizzy Gillespie", "Count Basie",
      "B.B. King", "Muddy Waters", "Howlin' Wolf", "Robert Johnson", "Buddy Guy",
      "Eric Clapton", "Jimi Hendrix", "Carlos Santana", "Stevie Ray Vaughan",
      "Bob Dylan", "Joni Mitchell", "Neil Young", "Paul Simon", "James Taylor",
      "Carole King", "Cat Stevens", "Janis Joplin", "Patti Smith", "Bruce Springsteen",
      "Tom Petty", "Fleetwood Mac", "The Eagles", "The Who", "The Doors",
      "Creedence Clearwater Revival", "The Beach Boys", "U2", "R.E.M.", "Radiohead",
      "Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains", "Foo Fighters",
      "Red Hot Chili Peppers", "Green Day", "Blink-182", "Linkin Park", "Coldplay",
      "Imagine Dragons", "OneRepublic", "Maroon 5", "The Killers",
      "Mumford & Sons", "Arcade Fire", "The Strokes", "Arctic Monkeys", "Kings of Leon",
      "Bohemian Rhapsody", "Stairway to Heaven", "Hotel California", "Imagine", "Hey Jude",
      "Billie Jean", "Like a Rolling Stone", "Smells Like Teen Spirit", "Sweet Child O' Mine", "Purple Haze",
      "Yesterday", "Superstition", "What's Going On", "Thriller", "Respect",
      "I Will Always Love You", "Rolling in the Deep", "Halo", "Someone Like You", "Uptown Funk",
      "Shape of You", "Bad Guy", "Blinding Lights", "Old Town Road", "Despacito",
      "Shake It Off", "Firework", "Just the Way You Are", "Can't Stop the Feeling!", "Sorry",
      "Havana", "Señorita", "No Tears Left to Cry", "Rockstar", "God's Plan"
    ],
    'Countries': [
      "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
      "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
      "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
      "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the",
      "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador",
      "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France",
      "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau",
      "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
      "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South",
      "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
      "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
      "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
      "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway",
      "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
      "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
      "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
      "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
      "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
      "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
      "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
    ],
    'Celebrities': [
      'Beyoncé',
      'Leonardo DiCaprio',
      'Oprah Winfrey',
      'Tom Hanks',
      'Meryl Streep',
      'Brad Pitt',
      'Angelina Jolie',
      'Will Smith',
      'Jennifer Lawrence',
      'Johnny Depp',
      'Adele',
      'Cristiano Ronaldo',
      'Emma Watson',
      'Dwayne Johnson',
      'Taylor Swift',
    ],
    'Professions': [
      'Doctor',
      'Teacher',
      'Engineer',
      'Chef',
      'Lawyer',
      'Pilot',
      'Accountant',
      'Architect',
      'Nurse',
      'Firefighter',
      'Journalist',
      'Photographer',
      'Electrician',
      'Farmer',
      'Dentist',
    ],
    'Science': [
      'Gravity',
      'Evolution',
      'Atom',
      'DNA',
      'Photosynthesis',
      'Quantum',
      'Relativity',
      'Antibiotics',
      'Cloning',
      'Fusion',
      'Black Hole',
      'Neuron',
      'Ecosystem',
      'Plate Tectonics',
      'Thermodynamics',
    ],
    'Technology': [
      'Artificial Intelligence',
      'Blockchain',
      'Virtual Reality',
      'Quantum Computing',
      '5G',
      'Internet of Things',
      'Robotics',
      'Cybersecurity',
      'Cloud Computing',
      'Machine Learning',
      'Nanotechnology',
      '3D Printing',
      'Augmented Reality',
      'Autonomous Vehicles',
      'Biometrics',
    ],
    'Literature': [
      'To Kill a Mockingbird',
      '1984',
      'Pride and Prejudice',
      'The Great Gatsby',
      'Moby Dick',
      'Hamlet',
      'The Catcher in the Rye',
      'Jane Eyre',
      'The Odyssey',
      'Don Quixote',
      'Fahrenheit 451',
      'Brave New World',
      'The Hobbit',
      'Frankenstein',
      'War and Peace',
    ],
    'History': [
      'World War II',
      'Renaissance',
      'Industrial Revolution',
      'French Revolution',
      'Civil Rights Movement',
      'Cold War',
      'Ancient Egypt',
      'Roman Empire',
      'American Revolution',
      'Silk Road',
      'Age of Exploration',
      'Enlightenment',
      'Fall of Berlin Wall',
      'Magna Carta',
      'Apollo 11',
    ],
    'Art': [
      'Mona Lisa',
      'Starry Night',
      'The Scream',
      'Guernica',
      'The Persistence of Memory',
      'Girl with a Pearl Earring',
      'The Last Supper',
      'The Birth of Venus',
      'American Gothic',
      'The Kiss',
      'Impressionism',
      'Cubism',
      'Surrealism',
      'Pop Art',
      'Abstract Expressionism',
    ],
    'TV Shows': [
      'Friends',
      'Game of Thrones',
      'Breaking Bad',
      'The Office',
      'Stranger Things',
      'The Simpsons',
      'Black Mirror',
      'The Crown',
      'Westworld',
      'Sherlock',
      'Seinfeld',
      'The Mandalorian',
      'Chernobyl',
      'Fargo',
      'Peaky Blinders',
    ],
    'Brands': [
      'Apple',
      'Coca-Cola',
      'Nike',
      'Google',
      'Amazon',
      'Microsoft',
      'Disney',
      'McDonald\'s',
      'Samsung',
      'Toyota',
      'Adidas',
      'Netflix',
      'Starbucks',
      'Ferrari',
      'LEGO',
    ],
    'Mythology': [
      'Zeus',
      'Thor',
      'Poseidon',
      'Ra',
      'Odin',
      'Athena',
      'Loki',
      'Hades',
      'Anubis',
      'Freya',
      'Hercules',
      'Medusa',
      'Minotaur',
      'Phoenix',
      'Kraken',
    ],
    'Video Games': [
      'Mario',
      'Minecraft',
      'Fortnite',
      'The Legend of Zelda',
      'Pac-Man',
      'Tetris',
      'Grand Theft Auto',
      'Pokémon',
      'Call of Duty',
      'Sonic the Hedgehog',
      'Final Fantasy',
      'The Sims',
      'World of Warcraft',
      'Portal',
      'Halo',
    ],
    'Nature': [
      'Rainforest',
      'Volcano',
      'Glacier',
      'Coral Reef',
      'Desert',
      'Waterfall',
      'Northern Lights',
      'Grand Canyon',
      'Great Barrier Reef',
      'Everest',
      'Tornado',
      'Geyser',
      'Redwood Forest',
      'Sahara',
      'Amazon River',
    ],
    'Fashion': [
      'Gucci',
      'Chanel',
      'Versace',
      'Louis Vuitton',
      'Prada',
      'Dior',
      'Armani',
      'Burberry',
      'Calvin Klein',
      'Ralph Lauren',
      'Haute Couture',
      'Vintage',
      'Streetwear',
      'Bohemian',
      'Minimalist',
    ],
    'Inventions': [
      'Wheel',
      'Telephone',
      'Light Bulb',
      'Internet',
      'Airplane',
      'Penicillin',
      'Printing Press',
      'Compass',
      'Steam Engine',
      'Television',
      'Radio',
      'Camera',
      'Computer',
      'Smartphone',
      'Telescope',
    ],
  };
}
