class Categories {
  static const List<String> allCategories = [
    'Animals',
    'Movies',
    'Food',
    'Sports',
    'Music',
    'Countries',
    'Celebrities',
    'Professions',
    'Science',
    'Technology',
    'Literature',
    'History',
    'Art',
    'TV Shows',
    'Brands',
    'Mythology',
    'Video Games',
    'Nature',
    'Fashion',
    'Inventions',
    'Act It Out',
    'Impressions',
    'Lord of the Rings',
    'Harry Potter',
    'Chess',
    'Bible',
    'Cornerstone',
    'Disney',
    'Olympic Sports',
    'Board Games',
  ];

  static const Map<String, List<String>> categoryWords = {
    'Animals': [
      'Elephant', 'Lion', 'Giraffe', 'Penguin', 'Kangaroo', 'Dolphin', 'Koala', 'Tiger', 'Panda', 'Cheetah',
      'Octopus', 'Platypus', 'Flamingo', 'Sloth', 'Narwhal', 'Rhinoceros', 'Hippopotamus', 'Zebra', 'Gorilla', 'Chimpanzee',
      'Orangutan', 'Leopard', 'Jaguar', 'Polar Bear', 'Grizzly Bear', 'Koala', 'Red Panda', 'Lemur', 'Meerkat', 'Raccoon',
      'Fox', 'Wolf', 'Coyote', 'Hyena', 'Jackal', 'Lynx', 'Bobcat', 'Mountain Lion', 'Panther', 'Cougar',
      'Ocelot', 'Serval', 'Caracal', 'Cheetah', 'Leopard', 'Snow Leopard', 'Jaguar', 'Tiger', 'Lion', 'Puma',
      'Elephant Seal', 'Sea Lion', 'Walrus', 'Manatee', 'Dugong', 'Whale Shark', 'Great White Shark', 'Hammerhead Shark', 'Manta Ray', 'Stingray',
      'Seahorse', 'Clownfish', 'Angelfish', 'Pufferfish', 'Swordfish', 'Marlin', 'Tuna', 'Salmon', 'Trout', 'Bass',
      'Catfish', 'Carp', 'Piranha', 'Barracuda', 'Moray Eel', 'Electric Eel', 'Jellyfish', 'Squid', 'Cuttlefish', 'Nautilus',
      'Lobster', 'Crab', 'Shrimp', 'Crayfish', 'Hermit Crab', 'Horseshoe Crab', 'Starfish', 'Sea Urchin', 'Sea Cucumber', 'Coral',
      'Anemone', 'Sponge', 'Barnacle', 'Mussel', 'Clam', 'Oyster', 'Scallop', 'Conch', 'Snail', 'Slug',
      'Butterfly', 'Moth', 'Dragonfly', 'Damselfly', 'Ladybug', 'Beetle', 'Ant', 'Bee', 'Wasp', 'Hornet',
      'Grasshopper', 'Cricket', 'Katydid', 'Praying Mantis', 'Stick Insect', 'Cockroach', 'Termite', 'Earwig', 'Flea', 'Louse',
      'Mosquito', 'Fly', 'Gnat', 'Midge', 'Firefly', 'Glowworm', 'Centipede', 'Millipede', 'Scorpion', 'Spider',
      'Tarantula', 'Black Widow', 'Daddy Long Legs', 'Tick', 'Mite', 'Worm', 'Leech', 'Planarian', 'Flatworm', 'Roundworm',
      'Tapeworm',
    ],
    'Movies': [
      'The Godfather', 'Citizen Kane', 'Casablanca', 'Schindler\'s List', 'Raging Bull', 'Gone with the Wind', 'Lawrence of Arabia', 'The Wizard of Oz', 'One Flew Over the Cuckoo\'s Nest', 'The Graduate',
      'On the Waterfront', 'Sunset Boulevard', 'It\'s a Wonderful Life', 'Star Wars', 'The Lord of the Rings', 'Pulp Fiction', 'Goodfellas', 'The Matrix', 'Forrest Gump', 'The Silence of the Lambs',
      'Apocalypse Now', 'Gladiator', 'Saving Private Ryan', 'Titanic', 'The Shawshank Redemption', 'Braveheart', 'The Dark Knight', 'Inception', 'The Green Mile', 'Fight Club',
      'The Usual Suspects', 'Jurassic Park', 'Back to the Future', 'The Lion King', 'Alien', 'Blade Runner', 'Terminator 2: Judgment Day', 'The Shining', 'Jaws', 'E.T. the Extra-Terrestrial',
      'Raiders of the Lost Ark', 'The Sixth Sense', 'The Exorcist', 'Psycho', 'Vertigo', 'North by Northwest', 'Rear Window', 'A Clockwork Orange', '2001: A Space Odyssey', 'The Departed',
      'Taxi Driver', 'American Beauty', 'Eternal Sunshine of the Spotless Mind', 'The Pianist', 'Memento', 'The Prestige', 'Amélie', 'Pan\'s Labyrinth', 'The Big Lebowski', 'No Country for Old Men',
      'There Will Be Blood', 'The Social Network', 'The King\'s Speech', 'Black Swan', 'Inglourious Basterds', 'The Grand Budapest Hotel', 'Whiplash', 'La La Land', 'Moonlight', 'Parasite',
      'The Shape of Water', 'Three Billboards Outside Ebbing, Missouri', 'Get Out', 'Lady Bird', 'Dunkirk', 'Mad Max: Fury Road', 'The Revenant', 'Birdman', 'Boyhood', '12 Years a Slave',
      'Gravity', 'Her', 'The Wolf of Wall Street', 'Django Unchained', 'The Artist', 'The Tree of Life', 'Inception', 'The Hurt Locker', 'Slumdog Millionaire', 'No Country for Old Men',
      'The Departed', 'Crash', 'Million Dollar Baby', 'The Lord of the Rings: The Return of the King', 'Chicago', 'A Beautiful Mind', 'Gladiator', 'American Beauty', 'Shakespeare in Love', 'Titanic',
      'The English Patient', 'Braveheart', 'Forrest Gump', 'Schindler\'s List', 'Unforgiven', 'The Silence of the Lambs', 'Dances with Wolves', 'Driving Miss Daisy', 'Rain Man', 'The Last Emperor',
      'Platoon', 'Out of Africa', 'Amadeus', 'Terms of Endearment', 'Gandhi', 'Chariots of Fire', 'Ordinary People', 'Kramer vs. Kramer', 'The Deer Hunter', 'Annie Hall',
      'Rocky', 'One Flew Over the Cuckoo\'s Nest', 'The Godfather Part II', 'The Sting', 'The Godfather', 'The French Connection', 'Patton', 'Midnight Cowboy', 'Oliver!', 'In the Heat of the Night',
      'A Man for All Seasons', 'The Sound of Music', 'My Fair Lady', 'Tom Jones', 'Lawrence of Arabia', 'West Side Story', 'The Apartment', 'Ben-Hur', 'Gigi', 'The Bridge on the River Kwai',
      'Around the World in 80 Days', 'Marty', 'On the Waterfront', 'From Here to Eternity', 'The Greatest Show on Earth', 'An American in Paris', 'All About Eve', 'All the King\'s Men', 'Hamlet', 'Gentleman\'s Agreement',
      'The Best Years of Our Lives', 'The Lost Weekend', 'Going My Way', 'Casablanca', 'Mrs. Miniver', 'How Green Was My Valley', 'Rebecca', 'Gone with the Wind', 'You Can\'t Take It with You', 'The Life of Emile Zola',
      'The Great Ziegfeld', 'Mutiny on the Bounty', 'It Happened One Night', 'Cavalcade', 'Grand Hotel', 'Cimarron', 'All Quiet on the Western Front', 'The Broadway Melody', 'Wings', 'Sunrise: A Song of Two Humans',
      'The Jazz Singer', 'Don Juan', 'The Big Parade', 'The Gold Rush', 'The Thief of Bagdad', 'The Ten Commandments', 'The Covered Wagon', 'The Four Horsemen of the Apocalypse', 'Way Down East', 'Intolerance',
    ],
    'Food': [
      'Pizza', 'Hamburger', 'Sushi', 'Pasta', 'Tacos', 'Fried Chicken', 'Steak', 'Ice Cream', 'Chocolate', 'Cheese',
      'Bacon', 'Eggs', 'Pancakes', 'Waffles', 'French Toast', 'Cereal', 'Oatmeal', 'Yogurt', 'Bagel', 'Croissant',
      'Donut', 'Muffin', 'Cupcake', 'Cake', 'Pie', 'Cookies', 'Brownies', 'Fudge', 'Caramel', 'Popcorn',
      'Chips', 'Pretzels', 'Nachos', 'Guacamole', 'Salsa', 'Hummus', 'Falafel', 'Pita Bread', 'Naan', 'Roti',
      'Curry', 'Biryani', 'Tandoori Chicken', 'Pad Thai', 'Spring Rolls', 'Dumplings', 'Fried Rice', 'Lo Mein', 'Chow Mein', 'General Tso\'s Chicken',
      'Kung Pao Chicken', 'Sweet and Sour Pork', 'Peking Duck', 'Dim Sum', 'Ramen', 'Udon', 'Soba', 'Tempura', 'Teriyaki', 'Miso Soup',
      'Pho', 'Banh Mi', 'Bun Bo Hue', 'Papaya Salad', 'Tom Yum Soup', 'Massaman Curry', 'Green Curry', 'Red Curry', 'Panang Curry', 'Satay',
      'Nasi Goreng', 'Rendang', 'Laksa', 'Hainanese Chicken Rice', 'Char Kway Teow', 'Chili Crab', 'Hokkien Mee', 'Roti Canai', 'Mee Goreng', 'Bak Kut Teh',
      'Paella', 'Gazpacho', 'Tortilla Española', 'Patatas Bravas', 'Chorizo', 'Jamón Ibérico', 'Manchego Cheese', 'Croquetas', 'Calamari', 'Gambas al Ajillo',
      'Lasagna', 'Risotto', 'Osso Buco', 'Gnocchi', 'Carbonara', 'Cacio e Pepe', 'Arancini', 'Bruschetta', 'Caprese Salad', 'Tiramisu',
      'Baguette', 'Quiche', 'Crème Brûlée', 'Escargot', 'Coq au Vin', 'Bouillabaisse', 'Ratatouille', 'Cassoulet', 'Beef Bourguignon', 'Macaron',
      'Schnitzel', 'Bratwurst', 'Sauerkraut', 'Spätzle', 'Kartoffelpuffer', 'Sauerbraten', 'Rouladen', 'Brezel', 'Apfelstrudel', 'Black Forest Cake',
      'Fish and Chips', 'Shepherd\'s Pie', 'Bangers and Mash', 'Full English Breakfast', 'Sunday Roast', 'Beef Wellington', 'Toad in the Hole', 'Sticky Toffee Pudding', 'Trifle', 'Eton Mess',
      'Haggis', 'Scotch Egg', 'Cornish Pasty', 'Welsh Rarebit', 'Lancashire Hotpot', 'Bubble and Squeak', 'Spotted Dick', 'Jam Roly-Poly', 'Battenberg Cake', 'Victoria Sponge',
      'Poutine', 'Maple Syrup', 'Butter Tart', 'Nanaimo Bar', 'Beaver Tail', 'Montreal-Style Bagel', 'Peameal Bacon', 'Tourtière', 'Bannock', 'Saskatoon Berry Pie',
      'Vegemite', 'Meat Pie', 'Pavlova', 'Lamington', 'Tim Tam', 'Anzac Biscuit', 'Fairy Bread', 'Kangaroo', 'Barramundi', 'Witchetty Grub',
      'Feijoada', 'Churrasco', 'Moqueca', 'Pão de Queijo', 'Brigadeiro', 'Acarajé', 'Coxinha', 'Farofa', 'Açaí Bowl', 'Guaraná',
      'Kimchi', 'Bibimbap', 'Bulgogi', 'Japchae', 'Samgyeopsal', 'Tteokbokki', 'Sundubu-jjigae', 'Samgyetang', 'Bossam', 'Hotteok',
      'Borscht', 'Beef Stroganoff', 'Pelmeni', 'Blini', 'Caviar', 'Shashlik', 'Olivier Salad', 'Kvass', 'Kasha', 'Pirozhki',
    ],
    'Sports': [
      "LeBron James", "Michael Jordan", "Tom Brady", "Lionel Messi", "Cristiano Ronaldo",
      "Serena Williams", "Roger Federer", "Tiger Woods", "Usain Bolt", "Simone Biles",
      "Rafael Nadal", "Novak Djokovic", "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo",
      "Kobe Bryant", "Shaquille O'Neal", "Wayne Gretzky", "Sidney Crosby", "Alex Ovechkin",
      "Mike Trout", "Mookie Betts", "Aaron Judge", "Bryce Harper", "Clayton Kershaw",
      "Patrick Mahomes", "Aaron Rodgers", "Drew Brees", "Russell Wilson", "Lamar Jackson",
      "Saquon Barkley", "Christian McCaffrey", "Ezekiel Elliott", "Derrick Henry", "Alvin Kamara",
      "Anthony Davis", "Kawhi Leonard", "James Harden", "Chris Paul", "Paul George",
      "Damian Lillard", "Russell Westbrook", "Kyrie Irving", "Luka Dončić", "Zion Williamson",
      "Joel Embiid", "Nikola Jokić", "Karl-Anthony Towns", "Devin Booker", "Jayson Tatum",
      "Jimmy Butler", "Klay Thompson", "Draymond Green", "Kemba Walker", "Trae Young",
      "Ja Morant", "Donovan Mitchell", "Rudy Gobert", "Bam Adebayo", "De'Aaron Fox",
      "Bradley Beal", "CJ McCollum", "Jrue Holiday", "Kyle Lowry", "Pascal Siakam",
      "Blake Griffin", "Andre Drummond", "Nikola Vučević", "Lauri Markkanen", "Kristaps Porziņģis",
      "DeMar DeRozan", "Zach LaVine", "John Wall", "Victor Oladipo", "D'Angelo Russell",
      "Brooklyn Nets", "Golden State Warriors", "Los Angeles Lakers", "Chicago Bulls", "Miami Heat",
      "Boston Celtics", "Philadelphia 76ers", "Milwaukee Bucks", "Toronto Raptors", "Houston Rockets",
      "Dallas Mavericks", "San Antonio Spurs", "Phoenix Suns", "Sacramento Kings", "Portland Trail Blazers",
      "Oklahoma City Thunder", "Utah Jazz", "Denver Nuggets", "Minnesota Timberwolves", "New Orleans Pelicans",
      "Atlanta Hawks", "Charlotte Hornets", "Washington Wizards", "Cleveland Cavaliers", "Detroit Pistons",
      "Indiana Pacers", "Orlando Magic", "New York Knicks", "Los Angeles Clippers", "Memphis Grizzlies",
      "New England Patriots", "Dallas Cowboys", "San Francisco 49ers", "Kansas City Chiefs", "Green Bay Packers",
      "Pittsburgh Steelers", "Seattle Seahawks", "Baltimore Ravens", "Chicago Bears", "Minnesota Vikings",
      "New Orleans Saints", "Buffalo Bills", "Tennessee Titans", "Indianapolis Colts", "Los Angeles Rams",
      "Cleveland Browns", "Tampa Bay Buccaneers", "Miami Dolphins", "Las Vegas Raiders", "Arizona Cardinals",
      "Washington Football Team", "New York Giants", "Philadelphia Eagles", "Denver Broncos", "Carolina Panthers",
      "Atlanta Falcons", "Detroit Lions", "Houston Texans", "Cincinnati Bengals", "Jacksonville Jaguars",
      "New York Yankees", "Los Angeles Dodgers", "Boston Red Sox", "Chicago Cubs", "San Francisco Giants",
      "St. Louis Cardinals", "Houston Astros", "Atlanta Braves", "New York Mets", "Philadelphia Phillies",
      "San Diego Padres", "Milwaukee Brewers", "Washington Nationals", "Minnesota Twins", "Cleveland Indians",
      "Chicago White Sox", "Cincinnati Reds", "Toronto Blue Jays", "Kansas City Royals", "Oakland Athletics",
      "Seattle Mariners", "Tampa Bay Rays", "Texas Rangers", "Los Angeles Angels", "Miami Marlins",
      "Arizona Diamondbacks", "Pittsburgh Pirates", "Colorado Rockies", "Baltimore Orioles", "Detroit Tigers",
      "Manchester United", "Liverpool FC", "FC Barcelona", "Real Madrid", "Chelsea FC",
      "Manchester City", "Paris Saint-Germain", "Juventus", "Bayern Munich", "AC Milan",
      "Inter Milan", "Arsenal FC", "Tottenham Hotspur", "Atletico Madrid", "Borussia Dortmund",
      "Ajax", "FC Porto", "Benfica", "AS Roma", "Lazio",
      "Napoli", "Sevilla FC", "Villarreal CF", "RB Leipzig", "PSV Eindhoven",
      "Olympique Lyonnais", "Marseille", "Club Brugge", "Shakhtar Donetsk", "Zenit Saint Petersburg",
      "Sporting CP", "Celtic FC", "Rangers FC", "Galatasaray", "Fenerbahçe",
      "Olympiacos", "AEK Athens", "CSKA Moscow", "Lokomotiv Moscow", "Besiktas",
      "Valencia CF", "Real Sociedad", "Eintracht Frankfurt", "Wolfsburg", "Borussia Mönchengladbach",
      "Soccer", "Basketball", "Baseball", "Tennis", "Golf", "Cricket", "Rugby", "American Football",
      "Hockey", "Table Tennis", "Badminton", "Volleyball", "Swimming", "Athletics", "Cycling",
      "Boxing", "Wrestling", "Gymnastics", "Martial Arts", "Surfing", "Skateboarding", "Skiing",
      "Snowboarding", "Equestrian", "Fencing", "Handball", "Lacrosse", "Rowing", "Sailing", "Softball",
      "Squash", "Triathlon", "Weightlifting", "Archery", "Darts", "Snooker", "Billiards", "Chess",
      "Polo", "Karate", "Judo", "Taekwondo", "Kendo", "Sumo", "Muay Thai", "Kickboxing", "MMA",
      "Formula 1", "NASCAR", "Rally", "IndyCar", "Speedway", "Tour de France", "Ironman", "Marathon",
      "Sprint", "Hurdles", "High Jump", "Long Jump", "Pole Vault", "Shot Put", "Discus", "Javelin",
      "Decathlon", "Pentathlon", "Heptathlon", "Biathlon", "Cross Country", "Nordic Combined",
      "Skeleton", "Luge", "Bobsleigh", "Curling", "Ice Skating", "Figure Skating", "Speed Skating",
      "Field Hockey", "Ice Hockey", "Water Polo", "Kayaking", "Canoeing", "Dragon Boat", "Synchronized Swimming",
      "Diving", "Platform Diving", "Springboard Diving", "Open Water Swimming", "Futsal", "Beach Volleyball",
      "Beach Soccer", "Footgolf", "Ultimate Frisbee", "Disc Golf", "Racquetball", "Paddle Tennis", "Pickleball",
      "Petanque", "Boules", "Bocce", "Kite Surfing", "Wind Surfing", "Wakeboarding", "Water Skiing", "Bodyboarding",
      "Sandboarding", "Mountain Biking", "Downhill Mountain Biking", "Freestyle BMX", "Flatland BMX",
      "Street Luge", "Roller Skating", "Roller Derby", "Parkour", "Freerunning", "Rock Climbing", "Bouldering",
      "Speed Climbing", "Sport Climbing", "Ice Climbing", "Caving", "Spelunking", "Orienteering", "Geocaching",
      "Rogaining", "Adventure Racing", "Obstacle Course Racing", "Mud Run", "Tough Mudder", "Spartan Race",
      "Strongman", "Powerlifting", "Bodybuilding", "CrossFit", "Highland Games", "E-Sports", "Video Game Tournaments",
    ],
    'Music': [
      "Pop", "Rock", "Hip Hop", "Rap", "Country", "Jazz", "Blues", "Classical",
      "Electronic", "Dance", "R&B", "Soul", "Reggae", "Funk", "Disco", "Heavy Metal",
      "Punk", "Alternative", "Indie", "Folk", "Gospel", "Opera", "Ska", "Bluegrass",
      "Latin", "Salsa", "Reggaeton", "Bachata", "Merengue", "Flamenco", "Afrobeat",
      "K-Pop", "J-Pop", "EDM", "House", "Techno", "Trance", "Dubstep", "Drum and Bass",
      "Trap", "Lo-fi", "Ambient", "New Age", "Synthwave", "Chillwave", "Grunge", "Britpop",
      "Post-rock", "Shoegaze", "Dream Pop", "Art Rock", "Progressive Rock", "Hard Rock",
      "Glam Rock", "Arena Rock", "Soft Rock", "Folk Rock", "Psychedelic Rock", "Symphonic Rock",
      "Rap Rock", "Industrial", "Noise", "Trip Hop", "Acoustic", "Unplugged", "Easy Listening",
      "Lounge", "Soundtrack", "Theme Music", "Instrumental", "A Cappella", "Vocal",
      "Baroque", "Renaissance", "Romantic", "Contemporary Classical", "Minimalism",
      "Experimental", "World Music", "Celtic", "Meditation Music", "Yoga Music",
      "Workout Music", "Chillout", "Deep House", "Future Bass", "Tropical House",
      "Electro Swing", "Moombahton", "Latin Trap", "Mariachi", "Ranchera", "Bolero",
      "Cumbia", "Tejano", "Norteño", "Tango", "Bossa Nova", "Samba", "Pagode", "Forró",
      "Frevo", "Axé", "Lambada", "Maracatu", "MPB (Música Popular Brasileira)",
      "Bach", "Mozart", "Beethoven", "Chopin", "Tchaikovsky", "Vivaldi", "Handel",
      "Debussy", "Ravel", "Gershwin", "Stravinsky", "Shostakovich", "Brahms", "Schubert",
      "Liszt", "Mendelssohn", "Dvorak", "Sibelius", "Mahler", "Rachmaninoff", "Paganini",
      "Elvis Presley", "The Beatles", "The Rolling Stones", "Led Zeppelin", "Pink Floyd",
      "Queen", "David Bowie", "Elton John", "Billy Joel", "Stevie Wonder", "Marvin Gaye",
      "James Brown", "Aretha Franklin", "Prince", "Michael Jackson", "Madonna", "Whitney Houston",
      "Mariah Carey", "Celine Dion", "Beyoncé", "Adele", "Rihanna", "Taylor Swift",
      "Katy Perry", "Lady Gaga", "Bruno Mars", "Justin Timberlake", "Ed Sheeran", "Sam Smith",
      "Ariana Grande", "Billie Eilish", "Shawn Mendes", "Dua Lipa", "Post Malone", "Drake",
      "Kanye West", "Jay-Z", "Eminem", "Snoop Dogg", "Kendrick Lamar", "Travis Scott",
      "Cardi B", "Nicki Minaj", "Megan Thee Stallion", "J. Cole", "Lil Wayne", "Nas",
      "Wu-Tang Clan", "Public Enemy", "N.W.A", "Run-D.M.C.", "LL Cool J", "Ice-T",
      "Outkast", "A Tribe Called Quest", "The Notorious B.I.G.", "2Pac", "50 Cent",
      "Usher", "Chris Brown", "Justin Bieber", "Shakira", "Jennifer Lopez", "Pitbull",
      "Enrique Iglesias", "Luis Fonsi", "Daddy Yankee", "Ozuna", "Bad Bunny", "J Balvin",
      "Maluma", "Ricky Martin", "Gloria Estefan", "Marc Anthony", "Juanes", "Carlos Vives",
      "Julio Iglesias", "Alejandro Sanz", "Camila Cabello", "Selena Gomez", "Demi Lovato",
      "Frank Sinatra", "Dean Martin", "Tony Bennett", "Nat King Cole", "Bing Crosby",
      "Ella Fitzgerald", "Billie Holiday", "Louis Armstrong", "Duke Ellington", "Miles Davis",
      "John Coltrane", "Charlie Parker", "Thelonious Monk", "Dizzy Gillespie", "Count Basie",
      "B.B. King", "Muddy Waters", "Howlin' Wolf", "Robert Johnson", "Buddy Guy",
      "Eric Clapton", "Jimi Hendrix", "Carlos Santana", "Stevie Ray Vaughan",
      "Bob Dylan", "Joni Mitchell", "Neil Young", "Paul Simon", "James Taylor",
      "Carole King", "Cat Stevens", "Janis Joplin", "Patti Smith", "Bruce Springsteen",
      "Tom Petty", "Fleetwood Mac", "The Eagles", "The Who", "The Doors",
      "Creedence Clearwater Revival", "The Beach Boys", "U2", "R.E.M.", "Radiohead",
      "Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains", "Foo Fighters",
      "Red Hot Chili Peppers", "Green Day", "Blink-182", "Linkin Park", "Coldplay",
      "Imagine Dragons", "OneRepublic", "Maroon 5", "The Killers",
      "Mumford & Sons", "Arcade Fire", "The Strokes", "Arctic Monkeys", "Kings of Leon",
      "Bohemian Rhapsody", "Stairway to Heaven", "Hotel California", "Imagine", "Hey Jude",
      "Billie Jean", "Like a Rolling Stone", "Smells Like Teen Spirit", "Sweet Child O' Mine", "Purple Haze",
      "Yesterday", "Superstition", "What's Going On", "Thriller", "Respect",
      "I Will Always Love You", "Rolling in the Deep", "Halo", "Someone Like You", "Uptown Funk",
      "Shape of You", "Bad Guy", "Blinding Lights", "Old Town Road", "Despacito",
      "Shake It Off", "Firework", "Just the Way You Are", "Can't Stop the Feeling!", "Sorry",
      "Havana", "Señorita", "No Tears Left to Cry", "Rockstar", "God's Plan"
    ],
    'Countries': [
      "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
      "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
      "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
      "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the",
      "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador",
      "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France",
      "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau",
      "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
      "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South",
      "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
      "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
      "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
      "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway",
      "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
      "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
      "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
      "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
      "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
      "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
      "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
    ],
  'Celebrities': [
      'Beyoncé',
      'Leonardo DiCaprio',
      'Oprah Winfrey',
      'Tom Hanks',
      'Meryl Streep',
      'Brad Pitt',
      'Angelina Jolie',
      'Will Smith',
      'Jennifer Lawrence',
      'Johnny Depp',
      'Adele',
      'Cristiano Ronaldo',
      'Emma Watson',
      'Dwayne Johnson',
      'Taylor Swift',
      'Rihanna',
      'Kim Kardashian',
      'Kanye West',
      'Lady Gaga',
      'Scarlett Johansson',
      'Robert Downey Jr.',
      'Chris Hemsworth',
      'Chris Evans',
      'Jennifer Aniston',
      'Sandra Bullock',
      'George Clooney',
      'Matt Damon',
      'Ben Affleck',
      'Natalie Portman',
      'Anne Hathaway',
      'Keanu Reeves',
      'Gal Gadot',
      'Justin Bieber',
      'Selena Gomez',
      'Shakira',
      'Drake',
      'Ariana Grande',
      'Bruno Mars',
      'Ed Sheeran',
      'Miley Cyrus',
      'Elon Musk',
      'Mark Zuckerberg',
      'Jeff Bezos',
      'Bill Gates',
      'Warren Buffett',
      'Lebron James',
      'Lionel Messi',
      'Serena Williams',
      'Roger Federer',
      'Usain Bolt',
      'Michael Phelps',
      'Simone Biles',
      'Conor McGregor',
      'Ellen DeGeneres',
      'Jimmy Fallon',
      'Stephen Colbert',
      'James Corden',
      'John Oliver',
      'Trevor Noah',
      'David Beckham',
      'Victoria Beckham',
      'Gordon Ramsay',
      'Jamie Oliver',
      'Reese Witherspoon',
      'Julia Roberts',
      'Kate Winslet',
      'Hugh Jackman',
      'Harrison Ford',
      'Morgan Freeman',
      'Tom Cruise',
      'Nicole Kidman',
      'Charlize Theron',
      'Emma Stone',
      'Ryan Reynolds',
      'Blake Lively',
      'Chadwick Boseman',
      'Chris Pratt',
      'Zoe Saldana',
      'Vin Diesel',
      'Jason Statham',
      'Jackie Chan',
      'Jet Li',
      'Michelle Yeoh',
      'Priyanka Chopra',
      'Deepika Padukone',
      'Shah Rukh Khan',
      'Amitabh Bachchan',
      'Ranveer Singh',
      'Kareena Kapoor',
      'Salman Khan',
      'Aishwarya Rai',
      'Hrithik Roshan',
      'Katrina Kaif',
      'Ajay Devgn',
      'Neymar',
    ],

    'Professions': [
        'Doctor',
        'Teacher',
        'Engineer',
        'Chef',
        'Lawyer',
        'Pilot',
        'Accountant',
        'Architect',
        'Nurse',
        'Firefighter',
        'Journalist',
        'Photographer',
        'Electrician',
        'Farmer',
        'Dentist',
        'Pharmacist',
        'Software Developer',
        'Police Officer',
        'Scientist',
        'Paramedic',
        'Veterinarian',
        'Biologist',
        'Chemist',
        'Civil Engineer',
        'Mechanical Engineer',
        'Aerospace Engineer',
        'Surgeon',
        'Psychologist',
        'Social Worker',
        'Librarian',
        'Graphic Designer',
        'Translator',
        'Real Estate Agent',
        'Plumber',
        'Carpenter',
        'Bartender',
        'Musician',
        'Actor',
        'Athlete',
        'Fashion Designer',
        'Interior Designer',
        'Economist',
        'Banker',
        'Investment Analyst',
        'Marketing Manager',
        'Sales Manager',
        'Human Resources Manager',
        'Public Relations Specialist',
        'Consultant',
        'Data Scientist',
        'Cybersecurity Specialist',
        'IT Support Specialist',
        'Web Developer',
        'Environmental Scientist',
        'Geologist',
        'Marine Biologist',
        'Urban Planner',
        'Event Planner',
        'Chiropractor',
        'Massage Therapist',
        'Physical Therapist',
        'Speech Therapist',
        'Occupational Therapist',
        'Pilot',
        'Flight Attendant',
        'Bus Driver',
        'Truck Driver',
        'Construction Worker',
        'Roofer',
        'Landscaper',
        'Surveyor',
        'Military Officer',
        'Navy Sailor',
        'Air Force Pilot',
        'Customs Officer',
        'Immigration Officer',
        'Diplomat',
        'Judge',
        'Prosecutor',
        'Defense Attorney',
        'Paralegal',
        'Legal Secretary',
        'Court Reporter',
        'Clergy',
        'Missionary',
        'Chaplain',
        'Pastor',
        'Rabbi',
        'Priest',
        'Imam',
        'Monk',
        'Nun',
        'Tour Guide',
        'Travel Agent',
        'Cruise Ship Director',
        'Hotel Manager',
        'Concierge',
        'Housekeeper',
        'Janitor',
        'Security Guard',
        'Bouncer',
        'Detective',
        'Private Investigator',
        'Forensic Scientist',
      ],

  'Science': [
      'Gravity',
      'Evolution',
      'Atom',
      'DNA',
      'Photosynthesis',
      'Quantum Mechanics',
      'Theory of Relativity',
      'Antibiotics',
      'Cloning',
      'Nuclear Fusion',
      'Black Hole',
      'Neuron',
      'Ecosystem',
      'Plate Tectonics',
      'Thermodynamics',
      'Electromagnetism',
      'Heliocentrism',
      'Genetics',
      'Big Bang Theory',
      'Cell Theory',
      'General Relativity',
      'Radioactivity',
      'Natural Selection',
      'Genetic Engineering',
      'Particle Physics',
      'CRISPR',
      'Dark Matter',
      'Superconductivity',
      'Nanotechnology',
      'Biotechnology',
      'Isaac Newton',
      'Albert Einstein',
      'Charles Darwin',
      'Marie Curie',
      'Nikola Tesla',
      'Galileo Galilei',
      'Stephen Hawking',
      'Louis Pasteur',
      'Richard Feynman',
      'Carl Sagan',
      'Rosalind Franklin',
      'James Watson',
      'Francis Crick',
      'Niels Bohr',
      'Erwin Schrödinger',
      'Michael Faraday',
      'Gregor Mendel',
      'Max Planck',
      'Werner Heisenberg',
      'Jane Goodall',
      'Ada Lovelace',
      'Dorothy Hodgkin',
      'Alan Turing',
      'J. Robert Oppenheimer',
      'Alexander Fleming',
    ],
    'Literature': [
      "To Kill a Mockingbird", "1984", "Pride and Prejudice", "The Great Gatsby", 
      "Moby Dick", "Hamlet", "The Catcher in the Rye", "Jane Eyre", 
      "The Odyssey", "Don Quixote", "Fahrenheit 451", "Brave New World", 
      "The Hobbit", "Frankenstein", "War and Peace", "Crime and Punishment", 
      "Wuthering Heights", "The Divine Comedy", "Anna Karenina", "The Brothers Karamazov", 
      "One Hundred Years of Solitude", "Ulysses", "The Iliad", "Great Expectations", 
      "The Adventures of Huckleberry Finn", "The Count of Monte Cristo", "Les Misérables", 
      "The Scarlet Letter", "Dracula", "The Grapes of Wrath", "Catch-22", 
      "The Lord of the Rings", "The Chronicles of Narnia", "A Tale of Two Cities", 
      "Middlemarch", "Alice's Adventures in Wonderland", "David Copperfield", "Madame Bovary", 
      "Lolita", "A Portrait of the Artist as a Young Man", "The Sun Also Rises", "Beloved", 
      "The Sound and the Fury", "Gone with the Wind", "Rebecca", "A Passage to India", 
      "Heart of Darkness", "Slaughterhouse-Five", "Lord of the Flies", "Of Mice and Men", 
      "Sense and Sensibility", "Mansfield Park", "Emma", "Northanger Abbey", 
      "Persuasion", "The Old Man and the Sea", "For Whom the Bell Tolls", 
      "The Call of the Wild", "White Fang", "East of Eden", "On the Road", 
      "In Search of Lost Time", "The Stranger", "The Trial", "Steppenwolf", 
      "Siddhartha", "Journey to the Center of the Earth", "Around the World in Eighty Days", 
      "Twenty Thousand Leagues Under the Sea", "The Time Machine", "The War of the Worlds", 
      "Brave New World", "The Picture of Dorian Gray", "A Clockwork Orange", 
      "Animal Farm", "Watership Down", "The Wind in the Willows", "The Secret Garden", 
      "Peter Pan", "The Jungle Book", "Treasure Island", "Gulliver's Travels", 
      "Robinson Crusoe", "The Three Musketeers", "The Hunchback of Notre-Dame", 
      "Ivanhoe", "The Canterbury Tales", "Beowulf", "The Epic of Gilgamesh", 
      "The Aeneid", "Metamorphoses", "The Republic", "The Prince", 
      "The Art of War", "The Federalist Papers", "The Communist Manifesto", 
      "The Wealth of Nations", "The Origin of Species", "The Interpretation of Dreams", 
      "The Souls of Black Folk", "Invisible Man", "Native Son", 
      "Things Fall Apart", "Cry, the Beloved Country", "The Color Purple", 
      "The Bell Jar", "To the Lighthouse", "Mrs. Dalloway", "Orlando", 
      "Brave New World", "The Road", "No Country for Old Men", "The Handmaid's Tale", 
      "The Blind Assassin", "Oryx and Crake", "The Testaments", "A Wrinkle in Time", 
      "The Giver", "Dune", "Foundation", "Neuromancer", 
      "Snow Crash", "The Left Hand of Darkness", "Do Androids Dream of Electric Sheep?", 
      "Ender's Game", "The Hitchhiker's Guide to the Galaxy", "2001: A Space Odyssey", 
      "The Dispossessed", "A Scanner Darkly", "Stranger in a Strange Land", 
      "The Forever War", "Hyperion", "I, Robot", "The Stars My Destination", 
      "Brave New World", "The Shining", "It", "The Stand", 
      "Carrie", "Misery", "Salem's Lot", "Pet Sematary", 
      "The Dark Tower", "The Green Mile", "Rita Hayworth and Shawshank Redemption", 
      "Different Seasons", "The Institute", "Doctor Sleep", 
      "The Outsider", "Under the Dome", "11/22/63", "The Tommyknockers"
  ],
    'History': [
      "World War II", "Renaissance", "Industrial Revolution", "French Revolution", 
      "Civil Rights Movement", "Cold War", "Ancient Egypt", "Roman Empire", 
      "American Revolution", "Silk Road", "Age of Exploration", "Enlightenment", 
      "Fall of Berlin Wall", "Magna Carta", "Apollo 11", "World War I", 
      "Great Depression", "Reformation", "Fall of the Roman Empire", 
      "Discovery of America", "Declaration of Independence", "Russian Revolution", 
      "Scientific Revolution", "Vietnam War", "Korean War", "The Crusades", 
      "Battle of Hastings", "Treaty of Versailles", "Atomic Bombings of Hiroshima and Nagasaki", 
      "Boston Tea Party", "Lewis and Clark Expedition", "Trail of Tears", 
      "Emancipation Proclamation", "Women's Suffrage", "Watergate Scandal", 
      "Pearl Harbor Attack", "The Black Death", "Spanish Inquisition", 
      "Opium Wars", "Meiji Restoration", "Fall of Constantinople", 
      "Hundred Years' War", "Treaty of Tordesillas", "Suez Crisis", 
      "D-Day", "Prohibition", "Berlin Airlift", "Montgomery Bus Boycott", 
      "Stonewall Riots", "Cuban Missile Crisis", "Assassination of Archduke Franz Ferdinand", 
      "Bay of Pigs Invasion", "Gulf War", "September 11 Attacks", 
      "Assassination of John F. Kennedy", "Lunar Landing", "Great Wall of China", 
      "Marco Polo's Travels", "Invention of the Printing Press", "Gutenberg Bible", 
      "Battle of Gettysburg", "Columbus' First Voyage", "Boston Massacre", 
      "Gold Rush", "Wright Brothers' First Flight", "Norman Conquest", 
      "Battle of Waterloo", "Napoleonic Wars", "Munich Agreement", 
      "Holocaust", "Sinking of the Titanic", "Mao's Long March", 
      "Partition of India", "Building of the Panama Canal", "Sputnik Launch", 
      "Chernobyl Disaster", "Assassination of Martin Luther King Jr.", "Bolshevik Revolution", 
      "Fall of Saigon", "Reign of Queen Elizabeth I", "Storming of the Bastille", 
      "Defeat of the Spanish Armada", "Fukushima Disaster", "Berlin Wall Construction", 
      "Battle of Midway", "Assassination of Abraham Lincoln", "Formation of the United Nations", 
      "Rosa Parks' Bus Protest", "Human Genome Project", "Space Race", 
      "Haitian Revolution", "Scramble for Africa", "Nelson Mandela's Release", 
      "Rwandan Genocide", "Bosnian War", "Manhattan Project", "Assassination of Julius Caesar", 
      "Formation of NATO", "Battle of Stalingrad", "Yalta Conference", 
      "Death of Alexander the Great", "Trial of Socrates", "Founding of Rome", 
      "Birth of Democracy in Athens", "Peloponnesian War", "Pax Romana", 
      "Construction of the Colosseum", "Destruction of Pompeii", "First Triumvirate", 
      "Reign of Augustus", "Reign of Nero", "Edict of Milan", 
      "Fall of the Western Roman Empire", "Viking Age", "Signing of the Magna Carta", 
      "Hundred Years' War", "War of the Roses", "Reign of Charlemagne", 
      "Rise of the Holy Roman Empire", "Age of Enlightenment", "French Revolution", 
      "Napoleonic Era", "Congress of Vienna", "Unification of Germany", 
      "Russian Revolution", "Formation of the Soviet Union", "Rise of Fascism", 
      "Spanish Civil War", "Establishment of Israel", "Cuban Revolution", 
      "Iranian Revolution", "End of Apartheid", "Arab Spring", 
      "Brexit", "Covid-19 Pandemic", "Invention of the Internet", "Rise of Social Media"
  ],
    'Art': [
      "Mona Lisa", "Starry Night", "The Scream", "Guernica", "The Persistence of Memory",
      "Girl with a Pearl Earring", "The Last Supper", "The Birth of Venus", "American Gothic",
      "The Kiss", "The Creation of Adam", "The Night Watch", "The Arnolfini Portrait",
      "The Garden of Earthly Delights", "The Hay Wain", "Whistler's Mother", "The Thinker",
      "The Great Wave off Kanagawa", "The School of Athens", "Liberty Leading the People",
      "Napoleon Crossing the Alps", "Las Meninas", "A Sunday Afternoon on the Island of La Grande Jatte",
      "Water Lilies", "Bal du moulin de la Galette", "The Third of May 1808",
      "The Raft of the Medusa", "Wanderer above the Sea of Fog", "Olympia", "The Sleeping Gypsy",
      "Christina's World", "The Two Fridas", "No. 5, 1948", "Blue Poles",
      "Campbell's Soup Cans", "Marilyn Diptych", "Fountain", "Composition VII",
      "Les Demoiselles d'Avignon", "Self-Portrait with Thorn Necklace and Hummingbird",
      "Sunflowers", "Irises", "Cafe Terrace at Night", "The Potato Eaters",
      "The Bedroom", "The Yellow House", "Portrait of Dr. Gachet", "At Eternity's Gate",
      "Almond Blossoms", "Wheatfield with Crows", "Road with Cypress and Star",
      "The Storm on the Sea of Galilee", "The Lacemaker", "The Milkmaid", "The Astronomer",
      "View of Delft", "The Little Street", "The Music Lesson", "The Art of Painting",
      "The Love Letter", "The Geographer", "Saint Jerome in His Study", "The Last Judgement",
      "The Ambassadors", "The Peasant Wedding", "Hunters in the Snow",
      "The Fight Between Carnival and Lent", "The Triumph of Death",
      "The Peasant Dance", "The Land of Cockaigne", "The Garden of Earthly Delights",
      "The Birth of Venus", "Primavera", "David", "Pieta", "Venus de Milo",
      "Winged Victory of Samothrace", "The Thinker", "The Gates of Hell", 
      "Liberty Leading the People", "The Persistence of Memory", "The Starry Night",
      "The Sistine Chapel Ceiling", "The Last Judgment", "The Arnolfini Portrait", 
      "Las Meninas", "Whistler's Mother", "The Thinker", "The Great Wave off Kanagawa",
      "Liberty Leading the People", "The Raft of the Medusa", "Olympia",
      "Christina's World", "The Two Fridas", "Campbell's Soup Cans", "Fountain",
      "Les Demoiselles d'Avignon", "Sunflowers", "Irises", "Cafe Terrace at Night",
      "The Potato Eaters", "The Bedroom", "Portrait of Dr. Gachet", "Almond Blossoms",
      "The Birth of Venus", "David", "Pieta", "Venus de Milo",
      "Winged Victory of Samothrace", "The Thinker"
  ],
    'TV Shows': [
      "Friends", "Game of Thrones", "Breaking Bad", "The Office", "Stranger Things", 
      "The Simpsons", "Black Mirror", "The Crown", "Westworld", "Sherlock", 
      "Seinfeld", "The Mandalorian", "Chernobyl", "Fargo", "Peaky Blinders", 
      "The Sopranos", "Mad Men", "The Wire", "Better Call Saul", "Parks and Recreation", 
      "Brooklyn Nine-Nine", "The Big Bang Theory", "How I Met Your Mother", "Lost", 
      "The Walking Dead", "Dexter", "True Detective", "House of Cards", "Narcos", 
      "Ozark", "Mindhunter", "Money Heist", "The Witcher", "The Boys", 
      "The Handmaid's Tale", "Big Little Lies", "The Marvelous Mrs. Maisel", "Succession", 
      "Boardwalk Empire", "Homeland", "24", "Prison Break", "Grey's Anatomy", 
      "ER", "House", "Scrubs", "This Is Us", "Supernatural", 
      "Buffy the Vampire Slayer", "Angel", "The X-Files", "Fringe", "Smallville", 
      "Arrow", "The Flash", "Legends of Tomorrow", "Supergirl", "Gotham", 
      "Lucifer", "Daredevil", "Jessica Jones", "Luke Cage", "Iron Fist", 
      "The Defenders", "The Punisher", "Agents of S.H.I.E.L.D.", "Agent Carter", 
      "WandaVision", "Loki", "Hawkeye", "Falcon and the Winter Soldier", "What If...?", 
      "Umbrella Academy", "Titans", "Doom Patrol", "The Sandman", "The Expanse", 
      "Battlestar Galactica", "Star Trek: The Next Generation", "Star Trek: Deep Space Nine", 
      "Star Trek: Voyager", "Star Trek: Discovery", "Star Trek: Picard", 
      "Doctor Who", "Torchwood", "Blackadder", "Monty Python's Flying Circus", 
      "The IT Crowd", "Downton Abbey", "Call the Midwife", "The Great British Bake Off", 
      "Luther", "Broadchurch", "Killing Eve", "Bodyguard", "Line of Duty", 
      "The Fall", "Happy Valley", "Top of the Lake", "Fleabag", "Veep", 
      "Arrested Development", "Community", "30 Rock", "Modern Family", "Schitt's Creek", 
      "The Good Place", "The Mindy Project", "Unbreakable Kimmy Schmidt", "New Girl", 
      "Glee", "Gilmore Girls", "One Tree Hill", "The OC", "Gossip Girl", 
      "Riverdale", "13 Reasons Why", "Euphoria", "Skins", "Misfits", 
      "The End of the F***ing World", "Sex Education", "Derry Girls", "Inbetweeners", 
      "Friday Night Lights", "Parenthood", "Six Feet Under", "Big Love", "The Leftovers", 
      "True Blood", "The Newsroom", "Silicon Valley", "Entourage", "Ballers", 
      "Eastbound & Down", "Curb Your Enthusiasm", "Louie", "Master of None", 
      "Atlanta", "Insecure", "Barry", "What We Do in the Shadows", "The Americans", 
      "Hannibal", "The Good Wife", "The Good Fight", "The West Wing", "Scandal", 
      "How to Get Away with Murder", "Law & Order", "Law & Order: SVU", "NCIS", 
      "CSI: Crime Scene Investigation", "Criminal Minds", "Bones", "Castle", 
      "Blue Bloods", "Magnum P.I.", "Hawaii Five-0", "MacGyver", "Person of Interest", 
      "Elementary", "Sherlock Holmes", "Lupin", "Endeavour", "Inspector Morse", 
      "Midsomer Murders", "Poirot", "Miss Marple", "Father Brown", "Grantchester", 
      "Death in Paradise", "Broadchurch", "The Bridge", "The Killing", "Borgen"
  ],
    'Brands': [
      "Apple", "Coca-Cola", "Nike", "Google", "Amazon", "Microsoft", "Disney", "McDonald's", 
      "Samsung", "Toyota", "Adidas", "Netflix", "Starbucks", "Ferrari", "LEGO",
      "Pepsi", "Intel", "BMW", "Mercedes-Benz", "Honda", "Ford", "Hyundai", "Chevrolet", 
      "Porsche", "Audi", "Nissan", "Volkswagen", "KFC", "Burger King", "Subway", 
      "Dunkin'", "Taco Bell", "Pizza Hut", "Domino's", "Chick-fil-A", "Walmart", 
      "Target", "Costco", "IKEA", "H&M", "Zara", "Louis Vuitton", "Gucci", 
      "Hermès", "Chanel", "Prada", "Versace", "Rolex", "Cartier", "Tiffany & Co.",
      "Under Armour", "New Balance", "Puma", "Reebok", "Vans", "Converse", "The North Face", 
      "Patagonia", "Columbia", "Sony", "Panasonic", "LG", "Toshiba", "Hitachi", 
      "JVC", "Canon", "Nikon", "Olympus", "GoPro", "Bose", "Beats by Dre", 
      "JBL", "Sennheiser", "Yamaha", "Philips", "Miele", "Dyson", "Whirlpool", 
      "General Electric", "Siemens", "Bosch", "Electrolux", "KitchenAid", "Maytag", 
      "Frigidaire", "All-Clad", "Cuisinart", "Breville", "DeLonghi", "Nespresso", 
      "Keurig", "Nestle", "Unilever", "Procter & Gamble", "Johnson & Johnson", 
      "Colgate-Palmolive", "L'Oréal", "Estee Lauder", "Clinique", "Lancome", 
      "Shiseido", "Dove", "Olay", "Neutrogena", "Nivea", "Garnier", 
      "Pantene", "Head & Shoulders", "Herbal Essences", "Gillette", "Oral-B", 
      "Braun", "Venus", "Old Spice", "Axe", "Degree", "Secret", 
      "Under Armour", "The North Face", "Patagonia", "Columbia", "Arc'teryx", 
      "Marmot", "Lululemon", "Athleta", "Gymshark", "Reebok", "Sketchers", 
      "Crocs", "Birkenstock", "Timberland", "Clarks", "Dr. Martens", 
      "Steve Madden", "Nine West", "Coach", "Michael Kors", "Kate Spade", 
      "Tory Burch", "Marc Jacobs", "Calvin Klein", "Ralph Lauren", "Tommy Hilfiger", 
      "Hugo Boss", "Armani", "Burberry", "Fendi", "Balenciaga", "Moncler", 
      "Canada Goose", "Stone Island", "Diesel", "Levi's", "Wrangler", 
      "Dockers", "Guess", "Abercrombie & Fitch", "Hollister", "American Eagle", 
      "GAP", "Banana Republic", "Old Navy", "Urban Outfitters", "Free People", 
      "Anthropologie", "Brandy Melville", "Victoria's Secret", "Bath & Body Works", "Lush",
      "Sephora", "Ulta", "Nordstrom", "Bloomingdale's", "Saks Fifth Avenue", "Neiman Marcus", 
      "Barneys New York", "Macy's", "JCPenney", "Kohl's", "TJ Maxx", 
      "Marshalls", "Ross", "Dollar General", "Dollar Tree", "Five Below", 
      "Best Buy", "Fry's Electronics", "Staples", "Office Depot", "OfficeMax", 
      "Home Depot", "Lowe's", "Menards", "Tractor Supply Co.", "Harbor Freight Tools", 
      "AutoZone", "O'Reilly Auto Parts", "Advance Auto Parts", "NAPA Auto Parts", "Carquest"
  ],
    'Mythology': [
      "Zeus", "Thor", "Poseidon", "Ra", "Odin", "Athena", "Loki", "Hades", "Freya", "Hercules",
      "Medusa", "Minotaur", "Phoenix", "Kraken", "Aphrodite", "Hera", "Apollo", "Artemis", 
      "Hephaestus", "Dionysus", "Hermes", "Demeter", "Ares", "Hestia", "Persephone", "Theseus", 
      "Achilles", "Orpheus", "Odysseus", "Jason", "Atlas", "Pandora", "Hel", "Fenrir", "Jormungandr", 
      "Baldur", "Tyr", "Heimdall", "Sif", "Njord", "Skadi", "Frigg", "Idun", "Bragi", "Ullr", 
      "Forseti", "Hermod", "Ran", "Aegir", "Norns", "Chiron", "Cerberus", "Hydra", "Cyclops", 
      "Sirens", "Scylla", "Charybdis", "Pegasus", "Gorgon", "Sphinx", "Chimera", "Banshee", 
      "Dryad", "Naiad", "Satyr", "Centaur", "Faun", "Griffin", "Harpy", "Basilisk", "Manticore", 
      "Dragon", "Wyvern", "Jotunn", "Valkyries", "Nidhogg", "Yggdrasil", "Asgard", "Midgard", 
      "Valhalla", "Frey", "Nerthus", "Mimir", "Ymir", "Skoll", "Hati", "Surtr", "Garm", 
      "Sigurd", "Brynhild", "Aeneas", "Romulus", "Remus", "Janus", "Jupiter", "Neptune", 
      "Pluto", "Venus", "Mars", "Mercury", "Diana", "Minerva", "Vesta", "Ceres", "Vulcan", 
      "Bacchus", "Saturn", "Proserpina", "Juno", "Cupid", "Aurora", "Sol", "Luna", "Mithras",
      "Bellona", "Discordia", "Faunus", "Flora", "Fortuna", "Hercules", "Luna", "Victoria",
      "Castor", "Pollux", "Lares", "Penates", "Numina", "Lupa", "Pomona", "Silvanus", 
      "Terminus", "Quirinus", "Genius", "Vulcan", "Vesta", "Aeneas", "Anchises", "Ascanius",
      "Latinus", "Turnus", "Lavinia", "Camilla", "Evander"
  ],
    'Video Games': [
      "Mario", "Minecraft", "Fortnite", "The Legend of Zelda", "Pac-Man", "Tetris", 
      "Grand Theft Auto", "Pokémon", "Call of Duty", "Sonic the Hedgehog", "Final Fantasy", 
      "The Sims", "World of Warcraft", "Portal", "Halo", "The Elder Scrolls V: Skyrim", 
      "Red Dead Redemption", "Animal Crossing", "Overwatch", "League of Legends", 
      "Counter-Strike", "Dota 2", "Resident Evil", "Metal Gear Solid", "Street Fighter", 
      "Mortal Kombat", "Super Smash Bros.", "Dark Souls", "Bloodborne", "The Witcher 3: Wild Hunt", 
      "BioShock", "Mass Effect", "Assassin's Creed", "Tomb Raider", "FIFA", 
      "NBA 2K", "Madden NFL", "Rocket League", "Starcraft", "Diablo", 
      "Kingdom Hearts", "Persona", "Splatoon", "Fallout", "Half-Life", 
      "Star Wars: Knights of the Old Republic", "Hearthstone", "Destiny", "Battlefield", "Far Cry", 
      "Uncharted", "God of War", "Crash Bandicoot", "Spyro the Dragon", "Castlevania", 
      "Mega Man", "Donkey Kong", "Kirby", "Metroid", "Fire Emblem", 
      "Xenoblade Chronicles", "Monster Hunter", "Dragon Quest", "Yakuza", "Bayonetta", 
      "Nier: Automata", "Hades", "Celeste", "Hollow Knight", "Stardew Valley", 
      "Undertale", "Cuphead", "Ori and the Blind Forest", "Journey", "The Last of Us", 
      "Fortnite", "PUBG", "Apex Legends", "Valorant", "Rainbow Six Siege", 
      "Genshin Impact", "Among Us", "Cyberpunk 2077", "Death Stranding", "Control", 
      "Dishonored", "Prey", "DOOM", "Wolfenstein", "Quake", 
      "Star Wars: Battlefront", "The Division", "Ghost Recon", "Watch Dogs", "For Honor", 
      "Tom Clancy's The Division", "Marvel's Spider-Man", "Ghost of Tsushima", "Sekiro: Shadows Die Twice", "Nioh", 
      "Dead by Daylight", "Phasmophobia", "Left 4 Dead", "Borderlands", "Overcooked", 
      "Divinity: Original Sin", "Baldur's Gate", "Pillars of Eternity", "Torchlight", "Grim Dawn", 
      "Path of Exile", "League of Legends", "Dota 2", "Team Fortress 2", "Smite", 
      "Paladins", "Heroes of the Storm", "Plants vs. Zombies", "Angry Birds", "Candy Crush Saga", 
      "Clash of Clans", "Clash Royale", "Guitar Hero", "Rock Band", "Dance Dance Revolution", 
      "Just Dance", "Wii Sports", "Wii Fit", "Ring Fit Adventure", "Beat Saber", 
      "VRChat", "The Climb", "Elite Dangerous", "No Man's Sky", "Minecraft Dungeons", 
      "Terraria", "Factorio", "Cities: Skylines", "SimCity", "Planet Coaster", 
      "RollerCoaster Tycoon", "The Sims 4", "Zoo Tycoon", "Age of Empires", "Civilization", 
      "Total War", "Europa Universalis", "Stellaris", "Crusader Kings", "Victoria", 
      "Hearts of Iron", "Kerbal Space Program", "Farming Simulator", "Train Simulator", "Microsoft Flight Simulator", 
      "Dirt Rally", "Gran Turismo", "Forza Horizon", "Need for Speed", "Burnout", 
      "Twisted Metal", "F-Zero", "Wipeout", "Mario Kart", "Crash Team Racing", 
      "Sonic & All-Stars Racing", "FIFA Street", "SSX", "Tony Hawk's Pro Skater", "Skate", 
      "NBA Jam", "NFL Blitz", "Mutant League Football", "Punch-Out!!", "Fight Night", 
      "UFC", "WWE 2K", "Boxing", "Karate Champ", "Virtua Fighter", "Age of Empires II",
  ],
    'Nature': [
      "Rainforest", "Volcano", "Glacier", "Coral Reef", "Desert", "Waterfall", "Northern Lights", 
      "Grand Canyon", "Great Barrier Reef", "Everest", "Tornado", "Geyser", "Redwood Forest", 
      "Sahara", "Amazon River", "Savannah", "Mangrove Forest", "Wetlands", "Tundra", 
      "Himalayas", "Andes", "Rocky Mountains", "Great Lakes", "Niagara Falls", 
      "Victoria Falls", "Mount Kilimanjaro", "Death Valley", "Angel Falls", "Galápagos Islands", 
      "Serengeti", "Patagonia", "Lake Baikal", "Dead Sea", "Mediterranean Sea", 
      "Baltic Sea", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", 
      "Antarctica", "Amazon Rainforest", "Borneo Rainforest", "Congo Rainforest", "Outback", 
      "Great Plains", "Mojave Desert", "Atacama Desert", "Namib Desert", "Kalahari Desert", 
      "Alps", "Pyrenees", "Appalachian Mountains", "Caucasus Mountains", "Carpathian Mountains", 
      "Danube River", "Nile River", "Yangtze River", "Mississippi River", "Ganges River", 
      "Yellowstone National Park", "Yosemite National Park", "Kruger National Park", "Banff National Park", "Fiordland National Park", 
      "Blue Hole", "Matterhorn", "Mount Fuji", "Mount Elbrus", 
      "Uluru", "Galápagos Islands", "Haleakalā", "Santorini", "Sundarbans", 
      "Ha Long Bay", "Mount Etna", "Mount Vesuvius", "Icelandic Hot Springs", "Plitvice Lakes", 
      "Lake Titicaca", "Loch Ness", "Isle of Skye", "New Zealand Fjords", "Bay of Fundy", 
      "Great Dividing Range", "Bora Bora", "Tahiti", "Azores", "Canary Islands", 
      "Madagascar", "Faroe Islands", "Scottish Highlands", "Daintree Rainforest", "Okavango Delta", 
      "Amazon Basin", "Pantanal", "Monteverde Cloud Forest", "Sossusvlei", "White Cliffs of Dover", 
      "Sinai Peninsula", "Galilee Sea", "Bora Bora", "Maui's Road to Hana", "Glacier National Park", 
      "Jasper National Park", "Dolomites", "Ben Nevis", "Ring of Kerry", "Cliffs of Moher", 
      "Moraine Lake", "Lofoten Islands", "Torres del Paine", "Mount Rainier", "Sierra Nevada", 
      "Mt. St. Helens", "Mount Cook", "Denali", "Everglades", "Hawaii Volcanoes National Park", 
      "Joshua Tree National Park", "Sequoia National Park", "Kings Canyon National Park", "Olympic National Park", "Redwood National and State Parks", 
      "Zion National Park", "Bryce Canyon National Park", "Arches National Park", "Capitol Reef National Park", "Canyonlands National Park"
  ],
  'Fashion': [
      "Gucci", "Chanel", "Versace", "Louis Vuitton", "Prada", "Dior", "Armani", "Burberry", 
      "Calvin Klein", "Ralph Lauren", "Haute Couture", "Vintage", "Streetwear", "Bohemian",
      "Balenciaga", "Hermès", "Yves Saint Laurent", "Givenchy", "Valentino", "Fendi",
      "Miu Miu", "Dolce & Gabbana", "Tom Ford", "Alexander McQueen", "Marc Jacobs",
      "Stella McCartney", "Vera Wang", "Michael Kors", "Oscar de la Renta", "Jean Paul Gaultier",
      "Salvatore Ferragamo", "Roberto Cavalli", "Kenzo", "Hugo Boss", "Moschino",
      "Tommy Hilfiger", "Lacoste", "Kate Spade", "Tory Burch", "Coach",
      "Victoria's Secret", "H&M", "Zara", "Uniqlo", "Forever 21",
      "Topshop", "Mango", "ASOS", "Bershka", "Stradivarius",
      "Reebok", "Adidas", "Nike", "Puma", "Under Armour",
      "Levi's", "Diesel", "Wrangler", "Dockers", "Guess",
      "Abercrombie & Fitch", "Hollister", "American Eagle", "GAP", "Banana Republic",
      "Urban Outfitters", "Free People", "Anthropologie", "Brandy Melville", "Lululemon",
      "Athleta", "J.Crew", "Madewell", "Ann Taylor", "LOFT",
      "Express", "New Balance", "Skechers", "Vans", "Converse",
      "Birkenstock", "Dr. Martens", "Timberland", "UGG", "Steve Madden",
      "Jimmy Choo", "Manolo Blahnik", "Christian Louboutin", "Giuseppe Zanotti", "Stuart Weitzman",
      "Sam Edelman", "Toms", "Hunter", "Nine West", "Aldo",
      "Chloé", "Celine", "Bottega Veneta", "Saint Laurent", "Balmain",
      "Off-White", "Supreme", "Palace", "A Bathing Ape", "Thom Browne",
      "Issey Miyake", "Comme des Garçons", "Rick Owens", "Maison Margiela", "Vetements",
      "Acne Studios", "Sacai", "JW Anderson", "Craig Green", "Raf Simons",
      "Phillip Lim", "Alexander Wang", "Public School", "Proenza Schouler", "Rodarte",
      "Jason Wu", "Carolina Herrera", "Moncler", "Canada Goose", "Patagonia",
      "The North Face", "Columbia", "Marmot", "Arc'teryx", "REI",
      "Hanes", "Fruit of the Loom", "Champion", "Gildan", "Jockey",
      "Victoria Beckham", "Sonia Rykiel", "Lanvin", "Chopard", "Van Cleef & Arpels",
      "Cartier", "Tiffany & Co.", "Pandora", "Swarovski", "Bvlgari",
      "David Yurman", "Harry Winston", "Graff", "Mikimoto", "Piaget",
      "TAG Heuer", "Rolex", "Omega", "Patek Philippe", "Breitling",
      "Longines", "Seiko", "Citizen", "Fossil", "Casio",
      "Swatch", "Ray-Ban", "Oakley", "Persol", "Warby Parker",
  ],
  'Inventions':  [
      "Wheel", "Telephone", "Light Bulb", "Internet", "Airplane", "Penicillin", "Printing Press", 
      "Compass", "Steam Engine", "Television", "Radio", "Camera", "Computer", "Smartphone", 
      "Telescope", "Microscope", "Refrigerator", "Electric Motor", "Battery", "Air Conditioning",
      "Automobile", "Helicopter", "Jet Engine", "Railroad", "Rocket", "Satellites", 
      "Submarine", "Radar", "Sonar", "X-ray Machine", "MRI Scanner", "CT Scanner", 
      "Vaccines", "Antibiotics", "Anesthesia", "DNA Sequencer", "Genetic Engineering", 
      "Nuclear Reactor", "Solar Panels", "Wind Turbine", "Electricity", "Alternating Current", 
      "Direct Current", "Transistor", "Integrated Circuit", "Microchip", "Laser", 
      "3D Printing", "GPS", "Bluetooth", "Wi-Fi", "Internet of Things", "Virtual Reality", 
      "Augmented Reality", "Drones", "Robotics", "Artificial Intelligence", "Machine Learning", 
      "Blockchain", "Cryptocurrency", "E-commerce", "Smart Home Devices", "Wearable Technology", 
      "Biometrics", "Self-driving Cars", "Space Shuttle", "Space Station", "Hubble Space Telescope", 
      "Mars Rover", "Electric Car", "Hybrid Car", "Fuel Cell", "Hydrogen Car", 
      "Hovercraft", "Maglev Train", "Segway", "Jet Pack", "Flying Car", 
      "Electric Scooter", "Electric Bike", "Solar Car", "Biodegradable Plastics", "Recycling Technology", 
      "Water Purification", "Desalination", "Air Purifier", "Nanotechnology", 
      "Gene Therapy", "CRISPR", "Telemedicine", "Smart Glasses", "Smart Watch", 
      "Fitness Tracker", "Smart TV", "Streaming Services", "Digital Music", "E-books", 
      "Online Education", "MOOCs", "Podcasting", "Social Media", "Cloud Computing", 
      "Big Data", "Data Analytics", "Quantum Computing", "Smart Grid", "Green Energy", 
      "Biofuels", "Vertical Farming", "Hydroponics", "Aquaponics", "Electric Fireplace", 
      "Induction Cooktop", "Smart Refrigerator", "Smart Oven", "Smart Dishwasher", 
      "Smart Washing Machine", "Home Automation", "Voice Assistants", "Home Security Systems", 
      "Smart Locks", "Smart Lighting", "Smart Thermostat", "Remote Control", 
      "Digital Cameras", "Smartphones", "Tablets", "E-readers", "Smart Speakers", 
      "Wireless Charging", "Portable Battery Pack", "Power Bank", "Smart Clothing", 
      "Smart Jewelry", "Fitness Apps", "Health Apps", "Personal Assistants", 
      "Smart Mirrors", "Smart Beds", "Home Workout Equipment", "Portable Projectors", 
      "VR Headsets", "AR Glasses", "Gaming Consoles", "Streaming Devices", 
      "Video Doorbells", "Smart Smoke Detectors", "Smart Water Sensors", "Leak Detectors", 
      "Smart Plugs", "Smart Outlets", "Smart Light Bulbs", "Smart Switches", 
      "Smart Blinds", "Smart Curtains", "Smart Garage Door Openers", "Robot Vacuums", 
      "Robot Mops", "Electric Toothbrushes", "Smart Scales", "Health Monitors", 
      "Sleep Trackers", "Pet Cameras", "Pet Feeders", "Pet Toys", 
      "Baby Monitors", "Smart Cribs", "Smart Baby Rockers", "Smart Baby Bottles", 
      "Smart Baby Monitors", "Smart Baby Thermometers", "Smart Baby Clothes", 
      "Smart Baby Toys", "Smart Baby Carriers", "Smart Baby Swings", 
      "Smart Baby High Chairs", "Smart Baby Strollers", "Smart Baby Bouncers"
    ],
    'Act It Out': [
      "Swimming", "Dancing", "Cooking", "Fishing", "Painting", "Juggling", "Skiing", "Surfing", 
      "Playing Guitar", "Typing", "Brushing Teeth", "Weightlifting", "Conducting Orchestra", 
      "Riding a Bicycle", "Tightrope Walking", "Karate", "Hula Hooping", "Swordfighting", 
      "Scuba Diving", "Rock Climbing", "Yoga", "Sleepwalking", "Miming", "Knitting", 
      "Cheerleading", "Driving a Car", "Flying a Plane", "Walking a Dog", "Skipping Rope", 
      "Playing Basketball", "Playing Soccer", "Playing Tennis", "Playing Baseball", "Playing Football", 
      "Reading a Book", "Writing", "Sewing", "Washing Dishes", "Vacuuming", "Ironing Clothes", 
      "Playing Video Games", "Watching TV", "Taking a Photo", "Using a Hammer", "Sawing Wood", 
      "Gardening", "Watering Plants", "Taking a Shower", "Jumping Jacks", "Push-Ups", 
      "Playing the Piano", "Playing the Drums", "Singing", "Blowing Up a Balloon", "Throwing a Frisbee", 
      "Playing Cards", "Drinking from a Cup", "Eating", "Digging", "Baking", "Skating", "Snowboarding", 
      "Playing Hockey", "Playing Volleyball", "Playing Golf", "Rowing a Boat", "Bowling", 
      "Playing Chess", "Playing Checkers", "Reading a Map", "Pitching a Tent", "Starting a Fire", 
      "Hiking", "Jumping Rope", "Climbing Stairs", "Parachuting", "Running", "Sneezing", 
      "Coughing", "Yawning", "Stretching", "Blowing Kisses", "Waving", "Thumb Wrestling", 
      "Giving a Thumbs Up", "High Fiving", "Nodding", "Shaking Head", "Hugging", "Dancing Ballet", 
      "Salsa Dancing", "Moonwalking", "Tap Dancing", "Playing Violin", "Playing Flute", "Playing Saxophone", 
      "Making a Call", "Texting", "Taking Selfies", "Walking in Heels", "Putting on Makeup", 
      "Brushing Hair", "Washing Face", "Filing Nails", "Catching a Ball", "Throwing a Ball", 
      "Swinging a Bat", "Swinging a Tennis Racket", "Lifting Weights", "Doing Sit-Ups", 
      "Skipping", "Leaping", "Twirling", "Spinning a Basketball", "Rolling a Bowling Ball", 
      "Playing with a Yo-Yo", "Riding a Skateboard", "Riding a Scooter", "Playing Maracas", 
      "Playing Tambourine", "Playing Harmonica", "Playing Accordion", "Playing Triangle", 
      "Conducting a Band", "Riding a Horse", "Doing the Robot Dance", "Breakdancing", "Tango Dancing", 
      "Waltzing", "Fencing", "Archery", "Flying a Kite", "Climbing a Ladder", "Pogo Sticking", 
      "Milking a Cow", "Picking Apples", "Serving Food", "Pantomiming", "Doing Laundry", 
      "Hanging Clothes", "Wrapping a Gift", "Opening a Gift", "Reading a Newspaper", "Writing a Letter", 
      "Mailing a Letter", "Knocking on a Door", "Opening a Door", "Closing a Door", "Unlocking a Door", 
      "Locking a Door", "Ringing a Doorbell", "Turning on a Light", "Turning off a Light", "Flipping a Switch", 
      "Setting an Alarm", "Hitting the Snooze Button", "Making a Bed", "Brushing a Pet", "Feeding a Pet"
  ],

  'Impressions': [
    "Donald Trump", "Elvis Presley", "Morgan Freeman", "Arnold Schwarzenegger", "Marilyn Monroe",
    "Sean Connery", "Darth Vader", "Yoda", "Homer Simpson", "Mickey Mouse",
    "Barack Obama", "Queen Elizabeth II", "Christopher Walken", "Jack Nicholson", "Marlon Brando",
    "Sylvester Stallone", "Robert De Niro", "Al Pacino", "Clint Eastwood", "Jim Carrey",
    "Michael Jackson", "Britney Spears", "Kermit the Frog", "Gollum", "Mr. Bean",
    "Charlie Chaplin", "Robin Williams", "Steve Irwin", "George W. Bush", "Bill Clinton",
    "Hank Hill", "Stewie Griffin", "Peter Griffin", "Lois Griffin", "Brian Griffin",
    "Quagmire", "Cleveland Brown", "Scooby-Doo", "Shaggy", "Popeye",
    "SpongeBob SquarePants", "Patrick Star", "Squidward", "Bart Simpson", "Marge Simpson",
    "Lisa Simpson", "Moe Szyslak", "Chief Wiggum", "Dr. Nick", "Apu Nahasapeemapetilon",
    "Mickey Mouse", "Goofy", "Donald Duck", "Winnie the Pooh", "Tigger",
    "Eeyore", "Piglet", "Buzz Lightyear", "Woody", "Mr. Potato Head",
    "Mrs. Doubtfire", "Gollum", "Gandalf", "Harry Potter", "Hermione Granger",
    "Ron Weasley", "Hagrid", "Professor Snape", "Dobby", "Voldemort",
    "Yogi Bear", "Boo-Boo Bear", "Fred Flintstone", "Barney Rubble", "George Jetson",
    "Elmer Fudd", "Bugs Bunny", "Daffy Duck", "Porky Pig", "Foghorn Leghorn",
    "Sylvester the Cat", "Tweety Bird", "Road Runner", "Wile E. Coyote", "Taz",
    "Johnny Bravo", "The Powerpuff Girls", "Professor Utonium", "Mojo Jojo", "Samurai Jack", "Aku",
    "Courage the Cowardly Dog", "Eustace Bagge", "Muriel Bagge", "The Joker", "Batman",
    "Superman", "Wonder Woman", "The Flash", "Aquaman", "Green Lantern",
    "Harley Quinn", "The Riddler", "Catwoman", "Penguin", "Bane",
    "Shrek", "Donkey from Shrek", "Fiona", "Lord Farquaad", "Puss in Boots",
    "Harry Potter", "Hermione Granger", "Ron Weasley", "Hagrid", "Dumbledore",
    "Professor McGonagall", "Professor Snape", "Draco Malfoy", "Luna Lovegood", "Neville Longbottom",
    "Dobby the House Elf", "Voldemort", "Sirius Black", "Remus Lupin", "Mad-Eye Moody", "Mark Zuckerberg",
  ],
  'Lord of the Rings': [
    'Frodo Baggins',
    'Gandalf',
    'Aragorn',
    'Legolas',
    'Gimli',
    'Samwise Gamgee',
    'Gollum',
    'Saruman',
    'Sauron',
    'Bilbo Baggins',
    'Boromir',
    'Elrond',
    'Galadriel',
    'Merry',
    'Pippin',
    'Éowyn',
    'Faramir',
    'Théoden',
    'Arwen',
    'The One Ring',
    'Mordor',
    'The Shire',
    'Rivendell',
    'Minas Tirith',
    'Rohan',
    'Isengard',
    'Mount Doom',
    'Balrog',
    'Nazgûl',
    'Orcs',
    'Ents',
    'Hobbits',
    'Elves',
    'Dwarves',
    'Wizards',
    'Uruk-hai',
    'Lothlorien',
    'Helm\'s Deep',
    'Gondor',
    'Ringwraiths',
    'Treebeard',
    'Weathertop',
    'Palantír',
    'Mithril',
    'Lembas bread',
    'Shadowfax',
    'Shelob',
    'Tom Bombadil',
    'Barrow-wights',
    'Bree',
    'Glorfindel',
    'Gondolin',
    'Numenor',
    'Beren',
    'Lúthien',
    'Celebrimbor',
    'Eärendil',
    'Sméagol',
    'Hama',
    'Grima Wormtongue',
    'Denethor',
    'Beregond',
    'Gondorian Soldiers',
    'Haldir',
    'Eomer',
    'Gamling',
    'Grimbold',
    'Elfhelm',
    'Gwaihir',
    'Radagast',
    'Kili',
    'Fili',
    'Thorin Oakenshield',
    'Dain Ironfoot',
    'Bard the Bowman',
    'Lake-town',
    'Dale',
    'Smaug',
    'Beorn',
    'Thranduil',
    'Mirkwood',
    'The Old Forest',
    'Fangorn Forest',
    'Dead Marshes',
    'Cirith Ungol',
    'Trolls',
    'Wargs',
    'Great Eagles',
    'Mouth of Sauron',
    'Witch-king of Angmar',
    'Dol Guldur',
    'Mirkwood Spiders',
    'Iron Hills',
    'Blue Wizards',
    'White Council',
    'Silmarils',
    'Ungoliant',
    'Ancalagon',
    'Glaurung',
    'Battle of Five Armies',
    'Battle of Pelennor Fields',
  ],
  'Harry Potter': [
    'Harry Potter',
    'Hermione Granger',
    'Ron Weasley',
    'Albus Dumbledore',
    'Severus Snape',
    'Voldemort',
    'Sirius Black',
    'Remus Lupin',
    'Minerva McGonagall',
    'Rubeus Hagrid',
    'Draco Malfoy',
    'Neville Longbottom',
    'Luna Lovegood',
    'Ginny Weasley',
    'Fred Weasley',
    'George Weasley',
    'Molly Weasley',
    'Arthur Weasley',
    'Bellatrix Lestrange',
    'Lucius Malfoy',
    'Narcissa Malfoy',
    'Dobby',
    'Kreacher',
    'Hogwarts',
    'Diagon Alley',
    'Hogsmeade',
    'Ministry of Magic',
    'Azkaban',
    'The Burrow',
    'Gringotts',
    'The Leaky Cauldron',
    'Platform 9¾',
    'The Forbidden Forest',
    'The Triwizard Tournament',
    'The Marauder\'s Map',
    'The Room of Requirement',
    'The Mirror of Erised',
    'The Philosopher\'s Stone',
    'The Chamber of Secrets',
    'The Prisoner of Azkaban',
    'The Goblet of Fire',
    'The Order of the Phoenix',
    'The Half-Blood Prince',
    'The Deathly Hallows',
    'Horcruxes',
    'The Elder Wand',
    'The Resurrection Stone',
    'The Invisibility Cloak',
    'The Sorting Hat',
    'Gryffindor',
    'Slytherin',
    'Ravenclaw',
    'Hufflepuff',
    'Quidditch',
    'The Golden Snitch',
    'The Nimbus 2000',
    'The Firebolt',
    'Butterbeer',
    'Polyjuice Potion',
    'Felix Felicis',
    'Mandrake',
    'Gillyweed',
    'Floo Powder',
    'The Knight Bus',
    'Buckbeak',
    'Aragog',
    'Nagini',
    'Basilisk',
    'Fawkes',
    'Hippogriff',
    'Dementors',
    'Thestrals',
    'House-elves',
    'Grindelwald',
    'Fleur Delacour',
    'Viktor Krum',
    'Cedric Diggory',
    'Mad-Eye Moody',
    'Dolores Umbridge',
    'Cornelius Fudge',
    'Rita Skeeter',
    'Xenophilius Lovegood',
    'Nymphadora Tonks',
    'Kingsley Shacklebolt',
    'Grawp',
    'Winky',
    'Borgin and Burkes',
    'Ollivanders',
    'Zonko\'s Joke Shop',
    'Honeydukes',
    'Madam Malkin\'s Robes',
    'Flourish and Blotts',
    'The Hog\'s Head',
    'The Three Broomsticks',
    'Shell Cottage',
    'Godric\'s Hollow',
    'Little Hangleton',
    'Spinner\'s End',
    'Malfoy Manor',
    'Number 4 Privet Drive',
    'The Dark Mark',
    'Death Eaters',
    'The Dursleys',
    'The Weasleys',
    'The Blacks',
    'The Malfoys',
    'The Potters',
    'The Grangers',
  ],
'Chess': [
    'King',
    'Queen',
    'Rook',
    'Bishop',
    'Knight',
    'Pawn',
    'Check',
    'Checkmate',
    'Stalemate',
    'Draw',
    'Castling',
    'En passant',
    'Promotion',
    'Opening',
    'Middlegame',
    'Endgame',
    'Gambit',
    'Sicilian Defense',
    'French Defense',
    'Ruy Lopez',
    'Caro-Kann Defense',
    'King\'s Indian Defense',
    'Queen\'s Gambit',
    'English Opening',
    'Italian Game',
    'Nimzo-Indian Defense',
    'Alekhine\'s Defense',
    'Benoni Defense',
    'Dutch Defense',
    'Grünfeld Defense',
    'Fianchetto',
    'Blitz Chess',
    'Bullet Chess',
    'Rapid Chess',
    'Classical Chess',
    'Chess Clock',
    'FIDE',
    'World Chess Championship',
    'Grandmaster',
    'International Master',
    'FIDE Master',
    'Candidate Master',
    'Elo Rating',
    'Chess Tournament',
    'Chessboard',
    'Chess Pieces',
    'Chess Notation',
    'Chess Engine',
    'Chess.com',
    'Lichess',
    'Magnus Carlsen',
    'Garry Kasparov',
    'Bobby Fischer',
    'Anatoly Karpov',
    'Vladimir Kramnik',
    'Viswanathan Anand',
    'Hikaru Nakamura',
    'Fabiano Caruana',
    'Ding Liren',
    'Ian Nepomniachtchi',
    'Alexander Alekhine',
    'Mikhail Tal',
    'Mikhail Botvinnik',
    'Jose Raul Capablanca',
    'Paul Morphy',
    'Judith Polgar',
    'Pillsbury Attack',
    'Fischer Random Chess',
    'Chess Olympiad',
    'Candidates Tournament',
    'Chess960',
    'King\'s Gambit',
    'Philidor Defense',
    'Scotch Game',
    'Four Knights Game',
    'Evans Gambit',
    'Petrov\'s Defense',
    'Dragon Variation',
    'Najdorf Variation',
    'Berlin Defense',
    'Kotov Syndrome',
    'Zugzwang',
    'Zwischenzug',
    'Tarrasch Rule',
    'Pawn Structure',
    'Opposition',
    'Fork',
    'Pin',
    'Skewer',
    'Discovered Attack',
    'Double Check',
    'Smothered Mate',
    'Back Rank Mate',
    'Underpromotion',
    'Chess Problems',
    'Simultaneous Exhibition',
    'Blindfold Chess',
    'Adjournment',
  ],
'Bible': [
    'Genesis',
    'Exodus',
    'Leviticus',
    'Numbers',
    'Deuteronomy',
    'Joshua',
    'Judges',
    'Ruth',
    '1 Samuel',
    '2 Samuel',
    '1 Kings',
    '2 Kings',
    '1 Chronicles',
    '2 Chronicles',
    'Ezra',
    'Nehemiah',
    'Esther',
    'Job',
    'Psalms',
    'Proverbs',
    'Ecclesiastes',
    'Song of Solomon',
    'Isaiah',
    'Jeremiah',
    'Lamentations',
    'Ezekiel',
    'Daniel',
    'Hosea',
    'Joel',
    'Amos',
    'Obadiah',
    'Jonah',
    'Micah',
    'Nahum',
    'Habakkuk',
    'Zephaniah',
    'Haggai',
    'Zechariah',
    'Malachi',
    'Matthew',
    'Mark',
    'Luke',
    'John',
    'Acts',
    'Romans',
    '1 Corinthians',
    '2 Corinthians',
    'Galatians',
    'Ephesians',
    'Philippians',
    'Colossians',
    '1 Thessalonians',
    '2 Thessalonians',
    '1 Timothy',
    '2 Timothy',
    'Titus',
    'Philemon',
    'Hebrews',
    'James',
    '1 Peter',
    '2 Peter',
    '1 John',
    '2 John',
    '3 John',
    'Jude',
    'Revelation',
    'Creation',
    'Adam and Eve',
    'Noah\'s Ark',
    'Tower of Babel',
    'Abraham',
    'Isaac',
    'Jacob',
    'Moses',
    'Ten Commandments',
    'Red Sea',
    'Promised Land',
    'Samson',
    'Delilah',
    'David',
    'Goliath',
    'Solomon',
    'Temple',
    'Babylonian Exile',
    'Prophets',
    'Messiah',
    'John the Baptist',
    'Virgin Mary',
    'Nativity',
    'Sermon on the Mount',
    'Parables',
    'Miracles',
    'Crucifixion',
    'Resurrection',
    'Ascension',
    'Pentecost',
    'Paul',
    'Epistles',
    'Armageddon',
    'Second Coming',
    'New Jerusalem',
    'Beatitudes',
    'Good Samaritan',
    'Prodigal Son',
    'Last Supper',
    'Garden of Gethsemane',
    'Judas Iscariot',
    'Pontius Pilate',
    'John the Apostle',
    'Thaddeus',
    'Matthew the Apostle',
    'Thomas the Apostle',
    'Philip the Apostle',
    'Simon the Zealot',
    'Bartholomew the Apostle',
    'Saul of Tarsus',
    'Stephen the Martyr',
    'Cornelius the Centurion',
    'Ethiopian Eunuch',
    'Barnabas',
    'Timothy',
    'Titus',
    'Lydia',
    'Priscilla and Aquila',
    'Apollos',
    'Revelation',
    'Four Horsemen',
    'Seven Seals',
    'Antichrist',
    'Lake of Fire',
    'Book of Life',
    'Alpha and Omega',
    'Tree of Life',
    'River of Life',
    'New Heaven',
    'New Earth',
    'Beast of the Sea',
    'Beast of the Earth',
    'False Prophet',
    'Great Tribulation',
    'Millennium',
    'Armageddon',
    'Great White Throne',
    'Jacob\'s Ladder',
    'Burning Bush',
    'Golden Calf',
    'Parting of the Red Sea',
    'Manna from Heaven',
    'Walls of Jericho',
    'Gideon\'s Fleece',
    'Samson',
    'David and Bathsheba',
    'Solomon\'s Wisdom',
    'Elijah and the Prophets of Baal',
    'Jonah and the Whale',
    'Daniel in the Lion\'s Den',
    'Shadrach, Meshach, and Abednego',
     'Jethro',
    'Jael',
    'Ehud',
    'Jepthah',
    'Abimelech',
    'Barak',
    'Deborah',
    'Sisera',
    'Tamar',
    'Rahab',
    'Gehazi',
    'Hagar',
    'Ishmael',
    'Lot',
    'Esau',
    'Rebekah',
    'Leah',
    'Rachel',
    'Laban',
    'Dinah',
    'Onan',
    'Potiphar',
    'Zipporah',
    'Balaam',
    'Balak',
    'Rahab',
    'Achan',
    'Sisera',
    'Barak',
    'Gideon',
    'Abimelech',
    'Tola',
    'Jair',
    'Jephthah',
    'Ibzan',
    'Elon',
    'Abdon',
    'Samson',
    'Delilah',
    'Eli',
    'Hannah',
    'Samuel',
    'Saul',
    'Jonathan',
    'Mephibosheth',
    'Joab',
    'Abner',
    'Bathsheba',
    'Uriah',
    'Absalom',
    'Adonijah',
    'Rehoboam',
    'Jeroboam',
    'Asa',
    'Jehoshaphat',
    'Ahab',
    'Jezebel',
    'Jehu',
    'Jehoiada',
    'Joash',
    'Amaziah',
    'Uzziah',
    'Hezekiah',
    'Manasseh',
    'Josiah',
    'Zedekiah',
    'Nebuchadnezzar',
    'Belshazzar',
    'Cyrus',
    'Darius',
    'Esther',
    'Mordecai',
    'Haman',
    'Nehemiah',
    'Ezra',
    'Sanballat',
    'Tobiah',
    'Eliphaz',
    'Bildad',
    'Zophar',
    'Elihu',
    'Satan',
    'Belial',
    'Leviathan',
    'Behemoth',
    'Methuselah',
    'Enoch',
    'Jubal',
    'Tubal-cain',
    'Shem',
    'Ham',
    'Japheth',
    'Terah',
    'Haran',
    'Nahor',
    'Melchizedek',
    'Keturah',
    'Lot\'s wife',
    'Moab',
    'Ammon',
    'Ishmaelites',
    'Midianites',
    'Amalekites',
    'Gibeonites',
    'Philistines',
    'Syrians',
    'Assyrians',
    'Babylonians',
    'Persians',
    'Medes',
    'Elamites',
    'Canaanites',
    'Hittites',
    'Hivites',
    'Jebusites',
    'Perizzites',
    'Girgashites',
    'Amorites',
    'Jesus',
    'Mary',
    'Joseph',
    'John the Baptist',
    'Peter',
    'John',
    'Andrew',
    'Philip',
    'Thomas',
    'Matthew',
    'Bartholomew',
    'Simon the Zealot',
    'Judas Iscariot',
    'Matthias',
    'Paul',
    'Barnabas',
    'Timothy',
    'Titus',
    'Luke',
    'Mark',
    'Mary Magdalene',
    'Martha',
    'Lazarus',
    'Zacchaeus',
    'Nicodemus',
    'Joseph of Arimathea',
    'Mary, mother of James',
    'Salome',
    'Cleopas',
    'Ananias',
    'Sapphira',
    'Stephen',
    'Philip the Evangelist',
    'Cornelius',
    'Silas',
    'Apollos',
    'Aquila',
    'Priscilla',
    'Lydia',
    'Dorcas (Tabitha)',
    'Eutychus',
    'Epaphras',
    'Philemon',
    'Onesimus',
    'Demas',
    'Aristarchus',
    'Tychicus',
    'Epaphroditus',
    'Euodia',
    'Syntyche',
    'Gaius',
    'Diotrephes',
    'Jude',
    'James, brother of Jesus',
    'Herod the Great',
    'Herod Antipas',
    'Pontius Pilate',
    'Caiaphas',
    'Elizabeth',
    'Zechariah',
    'Gabriel',
    'Simeon',
    'Anna',
    'Jairus',
    'Bartimaeus',
    'Simon of Cyrene',
    'Malchus',
    'Mary of Bethany',
    'Simon the Leper',
    'Nathanael',
    'Rhoda',
    'Herod Agrippa I',
    'Herod Agrippa II',
    'Felix',
    'Festus',
    'Gamaliel',
    'Saul of Tarsus',
    'Tertullus',
    'Elymas (Bar-Jesus)',
    'Sergius Paulus',
    'John Mark',
    'Alexander the coppersmith',
    'Diana (Artemis)',
    'Erastus',
    'Sosthenes',
    'Phoebe',
    'Junia',
    'Andronicus',
    'Mary, mother of John Mark',
    'Mnason',
    'Rufus',
    'Hermas',
    'Patrobas',
    'Hermes',
    'Philologus',
    'Julia',
    'Nereus',
    'Olympas',
    'Tertius',
    'Quartus',
    'Apelles',
    'Urbanus',
    'Stachys',
    'Amplias',
    'Tryphena',
    'Tryphosa',
    'Persis',
    'Asyncritus',
    'Phlegon',
    'Aristobulus',
    'Herodion',
    'Narcissus',
    'Melea',
    'Crescens',
    'Zenas',
    'Archippus',
    'Nymphas',
    'Demetrius',
    'Jason',
    'Sopater',
    'Trophimus',
    'Titus Justus',
    'Judas Barsabbas',
    'Manaen',
  ],
'Cornerstone': [
    'Jim Adams',
    'Jon Patton',
    'Charles Hart',
    'Jeff Larkin',
    'Tom Hall',
    'Rick Holman',
    'Michael Lowery',
    'Merl Miller',
    'Bob Neitz',
    'Ryan Olmstead',
    'Chad Adams',
    'Mikkelyn Adams',
    'Elijah Adams',
    'Eliana Adams',
    'Eva Adams',
    'Nancy Adams',
    'Melissa Allan',
    'William Andrews',
    'Steve Ardavanis',
    'Zac Ardavanis',
    'Dorothy Ashley',
    'Lois Avoian',
    'Terry Bachmeier',
    'John Bailey',
    'Shelley Bailey',
    'Patricia Baker',
    'Jonathan Baker',
    'Benjamin Baker',
    'David Barmore',
    'Sue Barnes',
    'Ethan Blake',
    'Grace Blake',
    'Annamarie Bower',
    'Ambrosia Bower',
    'Brently Bower',
    'Dee Bray',
    'Dana Brooks',
    'Kathryn Brooks',
    'Sarah Browning',
    'Jim Broyles',
    'Aden Broyles',
    'Jacob Broyles',
    'Matthew Broyles',
    'Eliana Broyles',
    'Gabriel Broyles',
    'Eric Broyles',
    'Dexter Broyles',
    'John Broyles',
    'Andrew Campbell',
    'Wally Cantrell',
    'Melissa Cantrell',
    'Loveta Cantrell',
    'Deanne Caoile',
    'Lex Caoile',
    'Betty Caruthers',
    'Don Covert',
    'Nona Covert',
    'Heather Cruz',
    'Ron Danielson',
    'Julie Danielson',
    'Randy Davis',
    'Julie Davis',
    'Mike Decious',
    'Catherine Decious',
    'Dean Degner',
    'Lori Degner',
    'Roy DeGroot',
    'Elaine DeGroot',
    'David Del Vescio',
    'Diane Del Vescio',
    'Vinicius Fontes',
    'Larissa Fontes',
    'Shane Gibbons',
    'Michael Gross',
    'Cheryl Gross',
    'Holly Hadley',
    'Tom Hall',
    'Mariú Hall',
    'Rick Hampton',
    'Sherri Hampton',
    'Charles Hart',
    'Lindsay Hart',
    'Elisha Hart',
    'Charlotte Hart',
    'David Henry',
    'Haley Hernandez',
    'Rick Holman',
    'Debbie Holman',
    'Jim Iversen',
    'Arnell Iversen',
    'Dan Iwicki',
    'Athena Iwicki',
    'Rob Johnston',
    'Nora Johnston',
    'Nick Jones',
    'Laura Jones',
    'Kate Jones',
    'Samantha Jones',
    'Andrew Kaufmann',
    'Marty Keffer',
    'Carla Keffer',
    'Vitaliy Khilkovich',
    'Alex Khilkovich',
    'Malakai Khilkovich',
    'Edward Kircher',
    'Suzan Kircher',
    'Al Koenig',
    'Ted Lamy',
    'Jeff Larkin',
    'Sheri Lewis',
    'Joe Lowery',
    'Jonna Lowery',
    'Michael Lowery',
    'Laura Lowery',
    'Dave Lucas',
    'Claudia Lucas',
    'Kassandra Luna',
    'Mike Marshall',
    'Ellie Marshall',
    'Pat Maurer',
    'Olga Melnytschk',
    'Billie Mercer',
    'Keith J. Miller',
    'Bethany Miller',
    'Evangeline Miller',
    'Keith Z. Miller',
    'Abraham Miller',
    'Isaiah Miller',
    'Merl Miller',
    'Tracy Miller',
    'Jonathan Miller',
    'Karen Mitchell',
    'Florence Mutyambai',
    'Bob Neitz',
    'Beryl Neitz',
    'Jeremy Nieman',
    'Bethany Nieman',
    'Michael Nieman',
    'Aubrey Nieman',
    'Sandi Nieman',
    'Ryan Olmstead',
    'Julie Olmstead',
    'Sam Olmstead',
    'Kaelyn Olmstead',
    'Thom Olmstead',
    'Sue Olmstead',
    'Grace Olsen',
    'Wyatt Parrish',
    'Deanna Parrish',
    'Aiden Parrish',
    'Darla Parrish',
    'Jon Patton',
    'Sarah Patton',
    'Rylynn Patton',
    'Noelle Patton',
    'Asa Patton',
    'Dave Perry',
    'Andrea Perry',
    'Josiah Peterson',
    'Rachelle Peterson',
    'Hosanna Peterson',
    'Nathaniel Peterson',
    'Evangeline Peterson',
    'Naomi Quinn',
    'Dean Rachwitz',
    'Lisa Rachwitz',
    'Jeff Reimer',
    'Debra Reimer',
    'Tad Reimer',
    'Tabitha Reimer',
    'Aaron Reimer',
    'Lynn Roosevelt',
    'Peter Ross',
    'Caren Ross',
    'Cory Ryan',
    'Melissa Ryan',
    'Calvin Ryan',
    'Peter Ryan',
    'Jonathan Ryan',
    'David Ryan',
    'Ila Sherer',
    'Barbie Smith',
    'Jim Smith',
    'Linda Smith',
    'Junior Solis',
    'Anastacia Solis',
    'Emmett Solis',
    'Korah Solis',
    'Josiah Solis',
    'Mike Tatreau',
    'Julie Tatreau',
    'Joel VanderHart',
    'Mary Beth VanderHart',
    'Marty Varns',
    'Hadassah Vergunst',
    'Irene Williams',
    'Marci Williams',
    'MJ Williams-Wells',
    'Randy Wyatt',
    'Nanette Wyatt',
    'Mitch Zamba',
    'Judi Zamba',
    'David Adams',
    'Daniela Adams',
    'Jonathan Adams',
    'Elisa Adams',
    'Andrea Adams',
    'Ashley Adams',
    'Alexandra Adams',
    'Simon Adams',
    'Tomi Ardiles',
    'Debbie Ardiles',
    'Carlie Ardiles',
    'Anya Ardiles',
    'Tyler Ardiles',
    'Zach Ardiles',
    'Gerrie Blose',
    'Candee Cain',
    'Nelson Cassaro',
    'Kristi Cassaro',
    'John Cavenaugh',
    'Norma Cavenaugh',
    'Ruth Dodd',
    'Jeanie Driscoll-Melhouse',
    'Dave Frankenberg',
    'Toni Frankenberg',
    'Audrey Frederickson',
    'Phil Fritschle',
    'Kevin Giammalva',
    'Kelli Giammalva',
    'Jesús Guardado',
    'Daisy Guardado',
    'Emmanuel Guardado',
    'Evangelina Guardado',
    'Elias Guardado',
    'Eliana Guardado',
    'Dick Hillyer',
    'Mary Ann Hillyer',
    'John Kitonga',
    'Priscilla Kitonga',
    'Samson Kitonga',
    'Ezekiel Kitonga',
    'David Kitonga',
    'Zola Kitonga',
    'John Kortie',
    'Bethanna Kortie',
    'Donna Lasslett',
    'Owen Matthess',
    'Allie Miller',
    'Michael Naaktgeboren',
    'Emily Naaktgeboren',
    'Karis Naaktgeboren',
    'Jed Naaktgeboren',
    'Ruth Naaktgeboren',
    'Emet Naaktgeboren',
    'Sharon Nestor',
    'Jonathan Phillips',
    'Reyna Phillips',
    'Cristina Phillips',
    'Josiah David Phillips',
    'Dennis Sanchez',
    'Lisa Sanchez',
    'Dean Skalberg',
    'Amy Skalberg',
    'Tristan Turner',
    'Patty Watts',
    'Noah Zamba',
    'Angéline Zamba',
    'Alexis Zamba',
    'Timothy Zamba',
    'Emma Zamba',
    'Oliver Zamba',
    'Eliza Zamba',
    'Theodore Zamba',
    'Marcelo Brondo',
    'Nancy Brondo',
    'Priscila Brondo',
    'Sam Masters',
    'Carita Masters',
    'Obed Rupertus',
    'Maria Teresa Rupertus',
    'David Adams',
    'Daniela Adams',
    'Baruch Maoz',
    'Bracha Maoz',
    'Antonio Escoto',
    'Cristian Escoto',
    'Danna Escoto',
    'Darianna Escoto',
    'Daenna Escoto',
    'Benjamin Escoto',
    'Eduardo Aricari',
    'Dolly Aricari',
    'Charis Aricari',
    'Izan Aricari',
    'Eliab Aricari',
    'Stephen Phillips',
    'Naíme Phillips',
    'Sebastian Phillips',
    'Stephen Phillips',
    'Naíme Elisa Phillips',
    'Sofia Phillips',
    'John Kortie',
    'Bethanna Kortie',
    'Terry Bachmeier',
    'Randy Wyatt'
],
'Disney': [
    'Sleeping Beauty Castle',
    'Pirates of the Caribbean',
    'Haunted Mansion',
    'It\'s a Small World',
    'Space Mountain',
    'Splash Mountain',
    'Big Thunder Mountain Railroad',
    'Indiana Jones Adventure',
    'Jungle Cruise',
    'Matterhorn Bobsleds',
    'Peter Pan\'s Flight',
    'Dumbo the Flying Elephant',
    'Mad Tea Party',
    'The Many Adventures of Winnie the Pooh',
    'Buzz Lightyear Astro Blasters',
    'Disneyland Railroad',
    'Main Street Electrical Parade',
    'Fantasmic!',
    'World of Color',
    'Mickey\'s PhilharMagic',
    'Enchanted Tiki Room',
    'Soarin\' Around the World',
    'Radiator Springs Racers',
    'Incredicoaster',
    'Pixar Pier',
    'Toy Story Midway Mania',
    'Disneyland Monorail',
    'Star Wars: Galaxy\'s Edge',
    'Snow White and the Seven Dwarfs',
    'Cinderella',
    'Sleeping Beauty',
    'The Little Mermaid',
    'Beauty and the Beast',
    'Aladdin',
    'The Lion King',
    'Pocahontas',
    'Mulan',
    'Tarzan',
    'Hercules',
    'Frozen',
    'Moana',
    'Tangled',
    'Zootopia',
    'Big Hero 6',
    'Wreck-It Ralph',
    'Toy Story',
    'Toy Story 2',
    'Toy Story 3',
    'Toy Story 4',
    'Finding Nemo',
    'Finding Dory',
    'Monsters, Inc.',
    'Monsters University',
    'Cars',
    'Cars 2',
    'Cars 3',
    'The Incredibles',
    'The Incredibles 2',
    'Ratatouille',
    'Brave',
    'Coco',
    'Up',
    'Wall-E',
    'Inside Out',
    'A Bug\'s Life',
    'The Good Dinosaur',
    'Mickey Mouse',
    'Minnie Mouse',
    'Donald Duck',
    'Daisy Duck',
    'Goofy',
    'Pluto',
    'Scrooge McDuck',
    'Huey',
    'Dewey',
    'Louie',
    'Chip',
    'Dale',
    'Cinderella',
    'Prince Charming',
    'Snow White',
    'Ariel',
    'Prince Eric',
    'Belle',
    'Beast',
    'Gaston',
    'Jasmine',
    'Aladdin',
    'Genie',
    'Jafar',
    'Mulan',
    'Li Shang',
    'Pocahontas',
    'John Smith',
    'Aurora',
    'Maleficent',
    'Rapunzel',
    'Flynn Rider',
    'Elsa',
    'Anna',
    'Olaf',
    'Kristoff',
    'Sven',
    'Moana',
    'Maui',
    'Simba',
    'Nala',
    'Mufasa',
    'Scar',
    'Timon',
    'Pumbaa',
    'Tarzan',
    'Jane',
    'Hercules',
    'Megara',
    'Phil',
    'Hades',
    'Peter Pan',
    'Tinker Bell',
    'Wendy',
    'Captain Hook',
    'Alice',
    'Mad Hatter',
    'Queen of Hearts',
    'Dumbo',
    'Bambi',
    'Thumper',
    'Pinocchio',
    'Jiminy Cricket',
    'Geppetto',
    'Lady',
    'Tramp',
    'Cruella de Vil',
    'Robin Hood',
    'Little John',
    'Winnie the Pooh',
    'Tigger',
    'Piglet',
    'Eeyore',
    'Christopher Robin',
    'Lilo',
    'Stitch',
    'Merida',
    'Tiana',
    'Prince Naveen',
    'Dr. Facilier',
    'Vanellope',
    'Ralph',
    'Buzz Lightyear',
    'Woody',
    'Jessie',
    'Mr. Incredible',
    'Elastigirl',
    'Violet',
    'Dash',
    'Jack-Jack',
    'Frozone',
    'Mike Wazowski',
    'Sully',
    'Boo',
    'Lightning McQueen',
    'Mater',
    'Remy',
    'Linguini',
    'Colette',
    'Anton Ego',
    'Wall-E',
    'EVE',
    'Carl Fredricksen',
    'Russell',
    'Dug',
    'Kevin',
    'Joy',
    'Sadness',
    'Anger',
    'Fear',
    'Disgust',
    'Miguel',
    'Hector',
    'Ernesto de la Cruz',
    'Dory',
    'Nemo',
    'Marlin',
    'Bruce',
    'King Triton',
    'Sebastian',
    'Flounder',
    'Ursula',
    'Prince Philip',
    'The Evil Queen',
    'Mother Gothel',
    'Drizella',
    'Anastasia',
    'Lady Tremaine',
    'The Fairy Godmother',
    'The Blue Fairy',
    'Pocahontas',
    'Meeko',
    'Flit',
    'Grandmother Willow',
    'Pegasus',
    'Louis',
    'Ray',
    'Mama Odie',
    'Pascal',
    'Maximus',
    'Hans',
    'Pua',
    'Hei Hei',
    'Te Fiti',
    'Rafiki',
    'Zazu',
    'Shenzi',
    'Banzai',
    'Ed',
    'Baloo',
    'Bagheera',
    'Shere Khan',
    'Kaa',
    'King Louie',
    'Mowgli',
    'Duchess',
    'Thomas O\'Malley',
    'Marie',
    'Toulouse',
    'Berlioz',
    'Bernard',
    'Bianca',
    'Evinrude',
    'Basil',
    'Dawson',
    'Ratigan',
    'Oliver',
    'Dodger',
    'Tito',
    'Georgette',
    'Flynn Rider',
    'Mother Gothel',
    'Elsa',
    'Anna',
    'Olaf',
    'Kristoff',
    'Ariel',
    'Ursula',
    'Sebastian',
    'Flounder',
    'King Triton',
    'Belle',
    'Beast',
    'Gaston',
    'Lumiere',
    'Cogsworth',
    'Mrs. Potts',
    'Chip',
    'Cinderella',
    'Lady Tremaine',
    'Drizella',
    'Anastasia',
    'The Fairy Godmother',
    'Shang',
    'Mushu',
    'John Smith',
    'Meeko',
    'Flit',
    'Megara',
    'Phil',
    'Hades',
    'Jane',
    'Terk',
    'Tantor',
    'Maid Marian',
    'Kanga',
    'Roo',
    'Gus',
    'Jaq',
    'Fairy Godmother',
    'Sulley',
    'Mike Wazowski',
    'Boo',
    'Woody',
    'Buzz Lightyear',
    'Jessie',
    'Rex',
    'Hamm',
    'Slinky Dog',
    'Mr. Potato Head',
    'Joy',
    'Sadness',
    'Anger',
    'Fear',
    'Disgust',
    'Marlin',
    'Dory',
    'Nemo',
    'Bruce',
    'Hank',
    'Bailey',
    'Destiny',
    'Lightning McQueen',
    'Mater',
    'Sally',
    'Doc Hudson',
    'Carl Fredricksen',
    'Russell',
    'Dug',
    'Kevin',
    'Remy',
    'Linguini',
    'Colette',
    'Anton Ego',
    'Merida',
    'Elinor',
    'Fergus',
    'Arlo',
    'Spot',
    'Miguel',
    'Hector',
    'Ernesto de la Cruz',
    'Tiana',
    'Naveen',
    'Louis',
    'Ray',
    'Hiro',
    'Baymax',
    'Go Go',
    'Wasabi',
    'Honey Lemon',
    'Fred',
    'Judy Hopps',
    'Nick Wilde',
],
'Olympic Sports': [
    'Archery',
    'Artistic Gymnastics',
    'Athletics',
    'Badminton',
    'Baseball',
    'Basketball',
    'Beach Volleyball',
    'Boxing',
    'Canoeing',
    'Cycling',
    'Diving',
    'Equestrian',
    'Fencing',
    'Field Hockey',
    'Football (Soccer)',
    'Golf',
    'Handball',
    'Judo',
    'Karate',
    'Modern Pentathlon',
    'Rowing',
    'Rugby Sevens',
    'Sailing',
    'Shooting',
    'Skateboarding',
    'Sport Climbing',
    'Surfing',
    'Swimming',
    'Table Tennis',
    'Taekwondo',
    'Tennis',
    'Trampoline Gymnastics',
    'Triathlon',
    'Volleyball',
    'Water Polo',
    'Weightlifting',
    'Wrestling',
    'Freestyle Wrestling',
    'Greco-Roman Wrestling',
    'Artistic Swimming',
    'BMX Racing',
    'BMX Freestyle',
    'Mountain Biking',
    'Road Cycling',
    'Track Cycling',
    'Marathon Swimming',
    'Open Water Swimming',
    'Rhythmic Gymnastics',
    'Synchronized Swimming',
    'Ice Hockey',
    'Alpine Skiing',
    'Biathlon',
    'Bobsleigh',
    'Cross-Country Skiing',
    'Curling',
    'Figure Skating',
    'Freestyle Skiing',
    'Ice Hockey',
    'Luge',
    'Nordic Combined',
    'Short Track Speed Skating',
    'Skeleton',
    'Ski Jumping',
    'Snowboarding',
    'Speed Skating',
],
'Board Games': [
    'Chess',
    'Checkers',
    'Backgammon',
    'Monopoly',
    'Scrabble',
    'Risk',
    'Clue (Cluedo)',
    'Catan (Settlers of Catan)',
    'Ticket to Ride',
    'Carcassonne',
    'Pandemic',
    'Battleship',
    'The Game of Life',
    'Sorry!',
    'Connect Four',
    'Candy Land',
    'Chutes and Ladders (Snakes and Ladders)',
    'Trivial Pursuit',
    'Pictionary',
    'Stratego',
    'Axis & Allies',
    'Agricola',
    'Dominion',
    'Puerto Rico',
    'Seven Wonders',
    'Power Grid',
    'Splendor',
    'Codenames',
    'Azul',
    'Dixit',
    'Forbidden Island',
    'Mansions of Madness',
    'Arkham Horror',
    'Eldritch Horror',
    'Betrayal at House on the Hill',
    'Gloomhaven',
    'Terraforming Mars',
    'Scythe',
    'Twilight Struggle',
    'Concordia',
    'Lords of Waterdeep',
    'King of Tokyo',
    'Small World',
    'Blood Rage',
    'Cyclades',
    'Tigris & Euphrates',
    'The Resistance',
    'Love Letter',
    'Camel Up',
    'Sheriff of Nottingham',
    'Memoir \'44',
    'Clank!',
    'Everdell',
    'Spirit Island',
    'Onitama',
    'Santorini',
    'Hive',
    'Patchwork',
    'Lost Cities',
    'Twilight Imperium',
    'Eclipse',
    'Brass: Birmingham',
    'Root',
    'Wingspan',
    'Calico',
    'The Crew: The Quest for Planet Nine',
    'Tapestry',
    'Roll for the Galaxy',
    'Race for the Galaxy',
    'Star Realms',
    'Terra Mystica',
    'Gaia Project',
    'Robinson Crusoe: Adventures on the Cursed Island',
    'Clans of Caledonia',
    'Great Western Trail',
    'The Quacks of Quedlinburg',
    'Underwater Cities',
    'Tzolk\'in: The Mayan Calendar',
    'Orléans',
    'The Castles of Burgundy',
    'Kingdomino',
    'Alhambra',
    'Stone Age',
    'Viticulture',
    'Arkham Horror: The Card Game',
    'Mage Knight',
    'Star Wars: Imperial Assault',
    'Dead of Winter',
    'Descent: Journeys in the Dark',
    'Marvel Champions: The Card Game',
],

  };
}
