class Categories {
  static const List<String> allCategories = [
    'Animals',
    'Movies',
    'Food',
    'Sports',
    'Music',
    'Countries',
  ];

  static const Map<String, List<String>> categoryWords = {
    'Animals': [
      'Elephant',
      'Lion',
      'Giraffe',
      'Penguin',
      'Kangaroo',
      'Dolphin',
      'Koala',
      'Tiger',
      'Panda',
      'Cheetah',
    ],
    'Movies': [
      'Star Wars',
      'Titanic',
      'Avatar',
      'Inception',
      'The Matrix',
      'Jurassic Park',
      'Forrest Gump',
      'The Godfather',
      'Pulp Fiction',
      'The Shawshank Redemption',
    ],
    'Food': [
      'Pizza',
      'Sushi',
      'Burger',
      'Pasta',
      'Tacos',
      'Ice Cream',
      'Chocolate',
      'Steak',
      'Curry',
      'Salad',
    ],
    'Sports': [
      'Football',
      'Basketball',
      'Tennis',
      'Golf',
      'Swimming',
      'Volleyball',
      'Soccer',
      'Cricket',
      'Rugby',
      'Boxing',
    ],
    'Music': [
      'Rock',
      'Pop',
      'Jazz',
      'Hip Hop',
      'Classical',
      'Country',
      'R&B',
      'Electronic',
      'Reggae',
      'Blues',
    ],
    'Countries': [
      'United States',
      'China',
      'India',
      'Brazil',
      'Russia',
      'Japan',
      'Germany',
      'United Kingdom',
      'France',
      'Italy',
    ],
  };
}