// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAHKOx1H8C5cKzZs2bM-jUJvV0YM9ieIE',
    appId: '1:566517912553:web:89984a6f8a0d6aa8c83178',
    messagingSenderId: '566517912553',
    projectId: 'heads-up-2ecfd',
    authDomain: 'heads-up-2ecfd.firebaseapp.com',
    storageBucket: 'heads-up-2ecfd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4k24prNbRFz8cOPNdNoRdtAe3ZSTTlzQ',
    appId: '1:566517912553:android:d92379f56deae1d6c83178',
    messagingSenderId: '566517912553',
    projectId: 'heads-up-2ecfd',
    storageBucket: 'heads-up-2ecfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK51uGONEwE_4yWFPX8QtLmxmAVe9eJeU',
    appId: '1:566517912553:ios:354bbd5a35d64e37c83178',
    messagingSenderId: '566517912553',
    projectId: 'heads-up-2ecfd',
    storageBucket: 'heads-up-2ecfd.firebasestorage.app',
    iosBundleId: 'com.example.headsUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK51uGONEwE_4yWFPX8QtLmxmAVe9eJeU',
    appId: '1:566517912553:ios:354bbd5a35d64e37c83178',
    messagingSenderId: '566517912553',
    projectId: 'heads-up-2ecfd',
    storageBucket: 'heads-up-2ecfd.firebasestorage.app',
    iosBundleId: 'com.example.headsUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAHKOx1H8C5cKzZs2bM-jUJvV0YM9ieIE',
    appId: '1:566517912553:web:af2bd1f8a57b953ac83178',
    messagingSenderId: '566517912553',
    projectId: 'heads-up-2ecfd',
    authDomain: 'heads-up-2ecfd.firebaseapp.com',
    storageBucket: 'heads-up-2ecfd.firebasestorage.app',
  );
}
